import { ScryfallCard } from "src";

const MyLaughterEchoes: ScryfallCard.Scheme = {
  object: "card",
  id: "e7d19c43-8c8d-404f-a7e7-b5205045b3b0",
  oracle_id: "c8653411-318b-41a9-8a74-f8b2ddd77892",
  multiverse_ids: [430657],
  tcgplayer_id: 132365,
  cardmarket_id: 298294,
  name: "My Laughter Echoes",
  lang: "en",
  released_at: "2017-06-16",
  uri: "https://api.scryfall.com/cards/e7d19c43-8c8d-404f-a7e7-b5205045b3b0",
  scryfall_uri: "https://scryfall.com/card/oe01/12%E2%98%85/my-laughter-echoes?utm_source=api",
  layout: "scheme",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/e/7/e7d19c43-8c8d-404f-a7e7-b5205045b3b0.jpg?1592766196",
    normal: "https://cards.scryfall.io/normal/front/e/7/e7d19c43-8c8d-404f-a7e7-b5205045b3b0.jpg?1592766196",
    large: "https://cards.scryfall.io/large/front/e/7/e7d19c43-8c8d-404f-a7e7-b5205045b3b0.jpg?1592766196",
    png: "https://cards.scryfall.io/png/front/e/7/e7d19c43-8c8d-404f-a7e7-b5205045b3b0.png?1592766196",
    art_crop: "https://cards.scryfall.io/art_crop/front/e/7/e7d19c43-8c8d-404f-a7e7-b5205045b3b0.jpg?1592766196",
    border_crop: "https://cards.scryfall.io/border_crop/front/e/7/e7d19c43-8c8d-404f-a7e7-b5205045b3b0.jpg?1592766196",
  },
  mana_cost: "",
  cmc: 0.0,
  type_line: "Ongoing Scheme",
  oracle_text:
    "(An ongoing scheme remains face up until it's abandoned.)\nWhenever you set a non-ongoing scheme in motion, you may abandon this scheme. If you do, set that scheme in motion again.",
  colors: [],
  color_identity: [],
  keywords: [],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "not_legal",
    gladiator: "not_legal",
    pioneer: "not_legal",
    explorer: "not_legal",
    modern: "not_legal",
    legacy: "not_legal",
    pauper: "not_legal",
    vintage: "not_legal",
    penny: "not_legal",
    commander: "not_legal",
    oathbreaker: "not_legal",
    brawl: "not_legal",
    historicbrawl: "not_legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "not_legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["paper"],
  reserved: false,
  foil: false,
  nonfoil: true,
  finishes: ["nonfoil"],
  oversized: true,
  promo: false,
  reprint: false,
  variation: false,
  set_id: "aa50a66a-0eb3-4bb5-acad-bc6c96f98663",
  set: "oe01",
  set_name: "Archenemy: Nicol Bolas Schemes",
  set_type: "archenemy",
  set_uri: "https://api.scryfall.com/sets/aa50a66a-0eb3-4bb5-acad-bc6c96f98663",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aoe01&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/oe01?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/e7d19c43-8c8d-404f-a7e7-b5205045b3b0/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Ac8653411-318b-41a9-8a74-f8b2ddd77892&unique=prints",
  collector_number: "12★",
  digital: false,
  rarity: "common",
  flavor_text: '"Groveling already? I\'m just starting to enjoy myself."',
  card_back_id: "1b2396d4-9048-439d-96bd-354288518841",
  artist: "Steve Argyle",
  artist_ids: ["a44ddda4-5331-4f83-aac9-3e00ed36bd7b"],
  illustration_id: "5362c4ee-eee9-4eaa-b8f2-e59b69432ba8",
  border_color: "black",
  frame: "2015",
  full_art: false,
  textless: false,
  booster: false,
  story_spotlight: false,
  prices: {
    usd: "0.86",
    usd_foil: null,
    usd_etched: null,
    eur: "0.10",
    eur_foil: null,
    tix: null,
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430657",
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=My+Laughter+Echoes&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=My+Laughter+Echoes&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=My+Laughter+Echoes",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/product/132365?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=My+Laughter+Echoes&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=My+Laughter+Echoes&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
