import { ScryfallCard } from "src";

const WilledIt: ScryfallCard.Scheme = {
  object: "card",
  id: "ab9016e5-f64f-4574-bf30-da0456b1ddec",
  oracle_id: "125b1dc2-020e-474e-8d8d-355b574dbddc",
  multiverse_ids: [430646],
  tcgplayer_id: 132355,
  cardmarket_id: 298306,
  name: "Because I Have Willed It",
  lang: "en",
  released_at: "2017-06-16",
  uri: "https://api.scryfall.com/cards/ab9016e5-f64f-4574-bf30-da0456b1ddec",
  scryfall_uri: "https://scryfall.com/card/oe01/1%E2%98%85/because-i-have-willed-it?utm_source=api",
  layout: "scheme",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/a/b/ab9016e5-f64f-4574-bf30-da0456b1ddec.jpg?1592766003",
    normal: "https://cards.scryfall.io/normal/front/a/b/ab9016e5-f64f-4574-bf30-da0456b1ddec.jpg?1592766003",
    large: "https://cards.scryfall.io/large/front/a/b/ab9016e5-f64f-4574-bf30-da0456b1ddec.jpg?1592766003",
    png: "https://cards.scryfall.io/png/front/a/b/ab9016e5-f64f-4574-bf30-da0456b1ddec.png?1592766003",
    art_crop: "https://cards.scryfall.io/art_crop/front/a/b/ab9016e5-f64f-4574-bf30-da0456b1ddec.jpg?1592766003",
    border_crop: "https://cards.scryfall.io/border_crop/front/a/b/ab9016e5-f64f-4574-bf30-da0456b1ddec.jpg?1592766003",
  },
  mana_cost: "",
  cmc: 0.0,
  type_line: "Ongoing Scheme",
  oracle_text:
    "(An ongoing scheme remains face up until it's abandoned.)\nSpells you cast cost {1} less to cast.\nAt the beginning of your opponents' end step, if they cast four or more spells this turn, abandon this scheme.",
  colors: [],
  color_identity: [],
  keywords: [],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "not_legal",
    gladiator: "not_legal",
    pioneer: "not_legal",
    explorer: "not_legal",
    modern: "not_legal",
    legacy: "not_legal",
    pauper: "not_legal",
    vintage: "not_legal",
    penny: "not_legal",
    commander: "not_legal",
    oathbreaker: "not_legal",
    brawl: "not_legal",
    historicbrawl: "not_legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "not_legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["paper"],
  reserved: false,
  foil: false,
  nonfoil: true,
  finishes: ["nonfoil"],
  oversized: true,
  promo: false,
  reprint: false,
  variation: false,
  set_id: "aa50a66a-0eb3-4bb5-acad-bc6c96f98663",
  set: "oe01",
  set_name: "Archenemy: Nicol Bolas Schemes",
  set_type: "archenemy",
  set_uri: "https://api.scryfall.com/sets/aa50a66a-0eb3-4bb5-acad-bc6c96f98663",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aoe01&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/oe01?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/ab9016e5-f64f-4574-bf30-da0456b1ddec/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A125b1dc2-020e-474e-8d8d-355b574dbddc&unique=prints",
  collector_number: "1★",
  digital: false,
  rarity: "common",
  card_back_id: "1b2396d4-9048-439d-96bd-354288518841",
  artist: "Adrian Majkrzak",
  artist_ids: ["80a893bb-e247-41f4-982d-a2a45a53ce15"],
  illustration_id: "c70b4169-a181-4676-9a5f-bd8d9894d586",
  border_color: "black",
  frame: "2015",
  full_art: false,
  textless: false,
  booster: false,
  story_spotlight: false,
  prices: {
    usd: "0.77",
    usd_foil: null,
    usd_etched: null,
    eur: "0.10",
    eur_foil: null,
    tix: null,
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430646",
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Because+I+Have+Willed+It&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Because+I+Have+Willed+It&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Because+I+Have+Willed+It",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/product/132355?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Because+I+Have+Willed+It&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Because+I+Have+Willed+It&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
