import { ScryfallCard } from "src";

const AbzanFalconer_Es: ScryfallCard.Normal = {
  object: "card",
  id: "6be15da4-cce8-4788-bce1-4de4bc83f839",
  oracle_id: "8b972819-507a-40a9-ab1f-1a674ea56083",
  multiverse_ids: [389158],
  name: "Abzan Falconer",
  printed_name: "Halconero abzano",
  lang: "es",
  released_at: "2014-09-26",
  uri: "https://api.scryfall.com/cards/6be15da4-cce8-4788-bce1-4de4bc83f839",
  scryfall_uri: "https://scryfall.com/card/ktk/2/es/halconero-abzano?utm_source=api",
  layout: "normal",
  highres_image: false,
  image_status: "lowres",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/6/b/6be15da4-cce8-4788-bce1-4de4bc83f839.jpg?1562788122",
    normal: "https://cards.scryfall.io/normal/front/6/b/6be15da4-cce8-4788-bce1-4de4bc83f839.jpg?1562788122",
    large: "https://cards.scryfall.io/large/front/6/b/6be15da4-cce8-4788-bce1-4de4bc83f839.jpg?1562788122",
    png: "https://cards.scryfall.io/png/front/6/b/6be15da4-cce8-4788-bce1-4de4bc83f839.png?1562788122",
    art_crop: "https://cards.scryfall.io/art_crop/front/6/b/6be15da4-cce8-4788-bce1-4de4bc83f839.jpg?1562788122",
    border_crop: "https://cards.scryfall.io/border_crop/front/6/b/6be15da4-cce8-4788-bce1-4de4bc83f839.jpg?1562788122",
  },
  mana_cost: "{2}{W}",
  cmc: 3.0,
  type_line: "Creature — Human Soldier",
  printed_type_line: "Criatura — Soldado humano",
  oracle_text:
    "Outlast {W} ({W}, {T}: Put a +1/+1 counter on this creature. Outlast only as a sorcery.)\nEach creature you control with a +1/+1 counter on it has flying.",
  printed_text:
    "Supervivencia {W}. ({W}, {T}: Pon un contador +1/+1 sobre esta criatura. Activa la habilidad de supervivencia solo como un conjuro.)\nCada criatura que controlas con un contador +1/+1 sobre ella tiene la habilidad de volar.",
  power: "2",
  toughness: "3",
  colors: ["W"],
  color_identity: ["W"],
  keywords: ["Outlast"],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "legal",
    gladiator: "legal",
    pioneer: "legal",
    explorer: "legal",
    modern: "legal",
    legacy: "legal",
    pauper: "not_legal",
    vintage: "legal",
    penny: "legal",
    commander: "legal",
    oathbreaker: "legal",
    brawl: "not_legal",
    historicbrawl: "legal",
    alchemy: "not_legal",
    paupercommander: "restricted",
    duel: "legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["paper", "mtgo"],
  reserved: false,
  foil: true,
  nonfoil: true,
  finishes: ["nonfoil", "foil"],
  oversized: false,
  promo: false,
  reprint: false,
  variation: false,
  set_id: "6c7a715c-ded9-449e-89b0-c665773e9c3c",
  set: "ktk",
  set_name: "Khans of Tarkir",
  set_type: "expansion",
  set_uri: "https://api.scryfall.com/sets/6c7a715c-ded9-449e-89b0-c665773e9c3c",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aktk&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/ktk?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/6be15da4-cce8-4788-bce1-4de4bc83f839/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A8b972819-507a-40a9-ab1f-1a674ea56083&unique=prints",
  collector_number: "2",
  digital: false,
  rarity: "uncommon",
  watermark: "abzan",
  flavor_text: "El camino más rápido para cruzar las dunas es por encima.",
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "Steven Belledin",
  artist_ids: ["f07d73b9-52a0-4fe5-858b-61f7b42174a5"],
  illustration_id: "3ef04134-5c97-48d1-b6fb-13273c091ddc",
  border_color: "black",
  frame: "2015",
  full_art: false,
  textless: false,
  booster: true,
  story_spotlight: false,
  edhrec_rank: 1330,
  penny_rank: 5354,
  prices: {
    usd: null,
    usd_foil: null,
    usd_etched: null,
    eur: null,
    eur_foil: null,
    tix: null,
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=389158&printed=true",
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Abzan+Falconer&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Abzan+Falconer&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Abzan+Falconer",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/search/magic/product?productLineName=magic&q=Abzan+Falconer&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall&view=grid",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Abzan+Falconer&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Abzan+Falconer&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
