import { ScryfallCard } from "src";

const PhyrexianArena: TestCard<ScryfallCard.Any> = {
  object: "card",
  id: "3b18d219-efde-4cc0-b955-cb71ead88023",
  oracle_id: "ee579a32-a048-4335-b966-231ba731cdea",
  multiverse_ids: [604746],
  tcgplayer_id: 479647,
  cardmarket_id: 694789,
  name: "Phyrexian Arena",
  printed_name: "|fyrs,CebDZFst.",
  lang: "ph",
  released_at: "2023-02-03",
  uri: "https://api.scryfall.com/cards/3b18d219-efde-4cc0-b955-cb71ead88023",
  scryfall_uri: "https://scryfall.com/card/one/283/%7Cfyrscebdzfst?utm_source=api",
  layout: "normal",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/3/b/3b18d219-efde-4cc0-b955-cb71ead88023.jpg?1689411727",
    normal: "https://cards.scryfall.io/normal/front/3/b/3b18d219-efde-4cc0-b955-cb71ead88023.jpg?1689411727",
    large: "https://cards.scryfall.io/large/front/3/b/3b18d219-efde-4cc0-b955-cb71ead88023.jpg?1689411727",
    png: "https://cards.scryfall.io/png/front/3/b/3b18d219-efde-4cc0-b955-cb71ead88023.png?1689411727",
    art_crop: "https://cards.scryfall.io/art_crop/front/3/b/3b18d219-efde-4cc0-b955-cb71ead88023.jpg?1689411727",
    border_crop: "https://cards.scryfall.io/border_crop/front/3/b/3b18d219-efde-4cc0-b955-cb71ead88023.jpg?1689411727",
  },
  mana_cost: "{1}{B}{B}",
  cmc: 3.0,
  type_line: "Enchantment",
  printed_type_line: "|myZJ.",
  oracle_text: "At the beginning of your upkeep, you draw a card and you lose 1 life.",
  printed_text: "|besYf,dceb&CpOnYA DEEstiYDC,co,GvEng mpreLYv,cosF,LFr1 QYCOt.",
  colors: ["B"],
  color_identity: ["B"],
  keywords: [],
  legalities: {
    standard: "legal",
    future: "legal",
    historic: "legal",
    gladiator: "legal",
    pioneer: "legal",
    explorer: "legal",
    modern: "legal",
    legacy: "legal",
    pauper: "not_legal",
    vintage: "legal",
    penny: "legal",
    commander: "legal",
    oathbreaker: "legal",
    brawl: "legal",
    historicbrawl: "legal",
    alchemy: "legal",
    paupercommander: "not_legal",
    duel: "legal",
    oldschool: "not_legal",
    premodern: "legal",
    predh: "legal",
  },
  games: ["paper", "mtgo", "arena"],
  reserved: false,
  foil: true,
  nonfoil: false,
  finishes: ["foil"],
  oversized: false,
  promo: true,
  reprint: true,
  variation: false,
  set_id: "04bef644-343f-4230-95ee-255f29aa67a2",
  set: "one",
  set_name: "Phyrexia: All Will Be One",
  set_type: "expansion",
  set_uri: "https://api.scryfall.com/sets/04bef644-343f-4230-95ee-255f29aa67a2",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aone&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/one?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/3b18d219-efde-4cc0-b955-cb71ead88023/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Aee579a32-a048-4335-b966-231ba731cdea&unique=prints",
  collector_number: "283",
  digital: false,
  rarity: "rare",
  watermark: "phyrexian",
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "Martina Fačková",
  artist_ids: ["6338124e-8e53-498d-8bf9-93a55db2f61c"],
  illustration_id: "282c97de-1967-4d6c-924d-6d139eb70b93",
  border_color: "black",
  frame: "2015",
  security_stamp: "oval",
  full_art: false,
  textless: false,
  booster: false,
  story_spotlight: false,
  promo_types: ["bundle"],
  edhrec_rank: 110,
  penny_rank: 175,
  preview: {
    source: "Wizards of the Coast",
    source_uri: "https://www.twitch.tv/videos/1710211245",
    previewed_at: "2023-01-17",
  },
  prices: {
    usd: null,
    usd_foil: "1.54",
    usd_etched: null,
    eur: null,
    eur_foil: "3.76",
    tix: null,
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=604746",
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Phyrexian+Arena&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Phyrexian+Arena&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Phyrexian+Arena",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/product/479647?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Phyrexian+Arena&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Phyrexian+Arena&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};

const PhyrexianArena_Unknown: ScryfallCard.Unknown = PhyrexianArena;
