import { ScryfallCard } from "src";

const Esper: ScryfallCard.Planar = {
  object: "card",
  id: "ffdf27d3-80b4-4aa1-b943-d247e502d32c",
  oracle_id: "4eebfaf3-18da-4661-b6a5-d874585e170a",
  multiverse_ids: [614932],
  tcgplayer_id: 490482,
  cardmarket_id: 705488,
  name: "Esper",
  lang: "en",
  released_at: "2023-04-21",
  uri: "https://api.scryfall.com/cards/ffdf27d3-80b4-4aa1-b943-d247e502d32c",
  scryfall_uri: "https://scryfall.com/card/moc/49/esper?utm_source=api",
  layout: "planar",
  highres_image: false,
  image_status: "lowres",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/f/f/ffdf27d3-80b4-4aa1-b943-d247e502d32c.jpg?1680815445",
    normal: "https://cards.scryfall.io/normal/front/f/f/ffdf27d3-80b4-4aa1-b943-d247e502d32c.jpg?1680815445",
    large: "https://cards.scryfall.io/large/front/f/f/ffdf27d3-80b4-4aa1-b943-d247e502d32c.jpg?1680815445",
    png: "https://cards.scryfall.io/png/front/f/f/ffdf27d3-80b4-4aa1-b943-d247e502d32c.png?1680815445",
    art_crop: "https://cards.scryfall.io/art_crop/front/f/f/ffdf27d3-80b4-4aa1-b943-d247e502d32c.jpg?1680815445",
    border_crop: "https://cards.scryfall.io/border_crop/front/f/f/ffdf27d3-80b4-4aa1-b943-d247e502d32c.jpg?1680815445",
  },
  mana_cost: "",
  cmc: 0.0,
  type_line: "Plane — Alara",
  oracle_text:
    "Artifact spells cost {1} less to cast.\nWhenever chaos ensues, creatures you control that are white, blue, and/or black become artifacts in addition to their other types until end of turn. Then each artifact creature you control gains vigilance, menace, and lifelink until end of turn.",
  colors: [],
  color_identity: [],
  keywords: [],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "not_legal",
    gladiator: "not_legal",
    pioneer: "not_legal",
    explorer: "not_legal",
    modern: "not_legal",
    legacy: "not_legal",
    pauper: "not_legal",
    vintage: "not_legal",
    penny: "not_legal",
    commander: "not_legal",
    oathbreaker: "not_legal",
    brawl: "not_legal",
    historicbrawl: "not_legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "not_legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["paper"],
  reserved: false,
  foil: false,
  nonfoil: true,
  finishes: ["nonfoil"],
  oversized: true,
  promo: false,
  reprint: false,
  variation: false,
  set_id: "6bba5de9-5afb-42af-a7eb-24ac854bf671",
  set: "moc",
  set_name: "March of the Machine Commander",
  set_type: "commander",
  set_uri: "https://api.scryfall.com/sets/6bba5de9-5afb-42af-a7eb-24ac854bf671",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Amoc&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/moc?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/ffdf27d3-80b4-4aa1-b943-d247e502d32c/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A4eebfaf3-18da-4661-b6a5-d874585e170a&unique=prints",
  collector_number: "49",
  digital: false,
  rarity: "common",
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "Bruce Brenneise",
  artist_ids: ["91d65465-e8a6-4a4e-8b0e-0e07466cfa0f"],
  illustration_id: "b6689314-0f56-4483-a214-e744fd0d55e5",
  border_color: "black",
  frame: "2015",
  full_art: false,
  textless: false,
  booster: false,
  story_spotlight: false,
  preview: {
    source: "Wizards of the Coast",
    source_uri: "https://magic.wizards.com/en/news/card-image-gallery/march-of-the-machine-planechase",
    previewed_at: "2023-03-29",
  },
  prices: {
    usd: "0.90",
    usd_foil: null,
    usd_etched: null,
    eur: "0.75",
    eur_foil: null,
    tix: null,
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=614932",
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Esper&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Esper&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Esper",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/product/490482?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Esper&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Esper&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
