import { ScryfallCard } from "src";

const MorphicTide: ScryfallCard.Planar = {
  object: "card",
  id: "54327aa2-319d-4430-a266-03cadeed6146",
  oracle_id: "302e4ac2-522b-4a0a-850a-d856639ea2a4",
  multiverse_ids: [423584],
  tcgplayer_id: 125605,
  cardmarket_id: 294398,
  name: "Morphic Tide",
  lang: "en",
  released_at: "2018-12-25",
  uri: "https://api.scryfall.com/cards/54327aa2-319d-4430-a266-03cadeed6146",
  scryfall_uri: "https://scryfall.com/card/opca/3/morphic-tide?utm_source=api",
  layout: "planar",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/5/4/54327aa2-319d-4430-a266-03cadeed6146.jpg?1547432267",
    normal: "https://cards.scryfall.io/normal/front/5/4/54327aa2-319d-4430-a266-03cadeed6146.jpg?1547432267",
    large: "https://cards.scryfall.io/large/front/5/4/54327aa2-319d-4430-a266-03cadeed6146.jpg?1547432267",
    png: "https://cards.scryfall.io/png/front/5/4/54327aa2-319d-4430-a266-03cadeed6146.png?1547432267",
    art_crop: "https://cards.scryfall.io/art_crop/front/5/4/54327aa2-319d-4430-a266-03cadeed6146.jpg?1547432267",
    border_crop: "https://cards.scryfall.io/border_crop/front/5/4/54327aa2-319d-4430-a266-03cadeed6146.jpg?1547432267",
  },
  mana_cost: "",
  cmc: 0.0,
  type_line: "Phenomenon",
  oracle_text:
    "When you encounter Morphic Tide, each player shuffles all permanents they own into their library, then reveals that many cards from the top of their library. Each player puts all artifact, creature, land, and planeswalker cards revealed this way onto the battlefield, then does the same for enchantment cards, then puts all cards revealed this way that weren't put onto the battlefield on the bottom of their library in any order. (Then planeswalk away from this phenomenon.)",
  colors: [],
  color_identity: [],
  keywords: [],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "not_legal",
    gladiator: "not_legal",
    pioneer: "not_legal",
    explorer: "not_legal",
    modern: "not_legal",
    legacy: "not_legal",
    pauper: "not_legal",
    vintage: "not_legal",
    penny: "not_legal",
    commander: "not_legal",
    oathbreaker: "not_legal",
    brawl: "not_legal",
    historicbrawl: "not_legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "not_legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["paper"],
  reserved: false,
  foil: false,
  nonfoil: true,
  finishes: ["nonfoil"],
  oversized: true,
  promo: false,
  reprint: true,
  variation: false,
  set_id: "ada3345c-d416-49bc-92e0-73363ddee5c8",
  set: "opca",
  set_name: "Planechase Anthology Planes",
  set_type: "planechase",
  set_uri: "https://api.scryfall.com/sets/ada3345c-d416-49bc-92e0-73363ddee5c8",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aopca&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/opca?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/54327aa2-319d-4430-a266-03cadeed6146/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A302e4ac2-522b-4a0a-850a-d856639ea2a4&unique=prints",
  collector_number: "3",
  digital: false,
  rarity: "common",
  card_back_id: "7840c131-f96b-4700-9347-2215c43156e6",
  artist: "Brandon Kitkouski",
  artist_ids: ["0330b5e8-2cf0-4ecb-8fd7-e20a18bdeb20"],
  illustration_id: "4fa395ac-c03a-414e-999d-331594553dd2",
  border_color: "black",
  frame: "2015",
  full_art: false,
  textless: false,
  booster: false,
  story_spotlight: false,
  prices: {
    usd: "3.64",
    usd_foil: null,
    usd_etched: null,
    eur: "1.18",
    eur_foil: null,
    tix: null,
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=423584",
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Morphic+Tide&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Morphic+Tide&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Morphic+Tide",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/product/125605?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Morphic+Tide&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Morphic+Tide&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
