import { ScryfallCard } from "src";

const TalonGates: ScryfallCard.Planar = {
  object: "card",
  id: "09feed09-96de-4208-b6b9-cac0ec150e70",
  oracle_id: "c85d3740-8c8d-4fef-ad33-a6f446b883ac",
  multiverse_ids: [423658],
  tcgplayer_id: 125634,
  cardmarket_id: 294472,
  name: "Talon Gates",
  lang: "en",
  released_at: "2018-12-25",
  uri: "https://api.scryfall.com/cards/09feed09-96de-4208-b6b9-cac0ec150e70",
  scryfall_uri: "https://scryfall.com/card/opca/77/talon-gates?utm_source=api",
  layout: "planar",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/0/9/09feed09-96de-4208-b6b9-cac0ec150e70.jpg?1547432225",
    normal: "https://cards.scryfall.io/normal/front/0/9/09feed09-96de-4208-b6b9-cac0ec150e70.jpg?1547432225",
    large: "https://cards.scryfall.io/large/front/0/9/09feed09-96de-4208-b6b9-cac0ec150e70.jpg?1547432225",
    png: "https://cards.scryfall.io/png/front/0/9/09feed09-96de-4208-b6b9-cac0ec150e70.png?1547432225",
    art_crop: "https://cards.scryfall.io/art_crop/front/0/9/09feed09-96de-4208-b6b9-cac0ec150e70.jpg?1547432225",
    border_crop: "https://cards.scryfall.io/border_crop/front/0/9/09feed09-96de-4208-b6b9-cac0ec150e70.jpg?1547432225",
  },
  mana_cost: "",
  cmc: 0.0,
  type_line: "Plane — Dominaria",
  oracle_text:
    "Any time you could cast a sorcery, you may exile a nonland card from your hand with X time counters on it, where X is its mana value. If the exiled card doesn't have suspend, it gains suspend. (At the beginning of its owner's upkeep, they remove a time counter. When the last is removed, the player casts it without paying its mana cost. If it's a creature, it has haste.)\nWhenever chaos ensues, remove two time counters from each suspended card you own.",
  colors: [],
  color_identity: [],
  keywords: [],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "not_legal",
    gladiator: "not_legal",
    pioneer: "not_legal",
    explorer: "not_legal",
    modern: "not_legal",
    legacy: "not_legal",
    pauper: "not_legal",
    vintage: "not_legal",
    penny: "not_legal",
    commander: "not_legal",
    oathbreaker: "not_legal",
    brawl: "not_legal",
    historicbrawl: "not_legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "not_legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["paper"],
  reserved: false,
  foil: false,
  nonfoil: true,
  finishes: ["nonfoil"],
  oversized: true,
  promo: false,
  reprint: true,
  variation: false,
  set_id: "ada3345c-d416-49bc-92e0-73363ddee5c8",
  set: "opca",
  set_name: "Planechase Anthology Planes",
  set_type: "planechase",
  set_uri: "https://api.scryfall.com/sets/ada3345c-d416-49bc-92e0-73363ddee5c8",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aopca&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/opca?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/09feed09-96de-4208-b6b9-cac0ec150e70/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Ac85d3740-8c8d-4fef-ad33-a6f446b883ac&unique=prints",
  collector_number: "77",
  digital: false,
  rarity: "common",
  card_back_id: "7840c131-f96b-4700-9347-2215c43156e6",
  artist: "Chippy",
  artist_ids: ["a36f01a0-e51a-48b2-a556-b9b3bc73f969"],
  illustration_id: "ce681b54-936a-4417-b021-564b6173a184",
  border_color: "black",
  frame: "2015",
  full_art: false,
  textless: false,
  booster: false,
  story_spotlight: false,
  prices: {
    usd: "2.30",
    usd_foil: null,
    usd_etched: null,
    eur: "1.95",
    eur_foil: null,
    tix: null,
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=423658",
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Talon+Gates&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Talon+Gates&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Talon+Gates",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/product/125634?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Talon+Gates&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Talon+Gates&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
