import { ScryfallCard } from "src";

const Monkey: TestCard<ScryfallCard.Augment> = {
  object: "card",
  id: "b4d54442-caca-412d-a716-032eaa587944",
  oracle_id: "45f13c9d-cdbe-42c4-9563-cf539fe7e075",
  multiverse_ids: [439546],
  tcgplayer_id: 153183,
  cardmarket_id: 314011,
  name: "Robo-",
  lang: "en",
  released_at: "2017-12-08",
  uri: "https://api.scryfall.com/cards/b4d54442-caca-412d-a716-032eaa587944",
  scryfall_uri: "https://scryfall.com/card/ust/157/robo-?utm_source=api",
  layout: "augment",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/b/4/b4d54442-caca-412d-a716-032eaa587944.jpg?1572374695",
    normal: "https://cards.scryfall.io/normal/front/b/4/b4d54442-caca-412d-a716-032eaa587944.jpg?1572374695",
    large: "https://cards.scryfall.io/large/front/b/4/b4d54442-caca-412d-a716-032eaa587944.jpg?1572374695",
    png: "https://cards.scryfall.io/png/front/b/4/b4d54442-caca-412d-a716-032eaa587944.png?1572374695",
    art_crop: "https://cards.scryfall.io/art_crop/front/b/4/b4d54442-caca-412d-a716-032eaa587944.jpg?1572374695",
    border_crop: "https://cards.scryfall.io/border_crop/front/b/4/b4d54442-caca-412d-a716-032eaa587944.jpg?1572374695",
  },
  mana_cost: "",
  cmc: 0.0,
  type_line: "Artifact Creature — Construct",
  oracle_text:
    "At the beginning of each end step, if an artifact entered the battlefield under your control this turn,\nAugment {2} ({2}, Reveal this card from your hand: Combine it with target host. Augment only as a sorcery.)",
  power: "+1",
  toughness: "+1",
  colors: [],
  color_identity: [],
  keywords: ["Augment"],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "not_legal",
    gladiator: "not_legal",
    pioneer: "not_legal",
    explorer: "not_legal",
    modern: "not_legal",
    legacy: "not_legal",
    pauper: "not_legal",
    vintage: "not_legal",
    penny: "not_legal",
    commander: "not_legal",
    oathbreaker: "not_legal",
    brawl: "not_legal",
    historicbrawl: "not_legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "not_legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["paper"],
  reserved: false,
  foil: true,
  nonfoil: true,
  finishes: ["nonfoil", "foil"],
  oversized: false,
  promo: false,
  reprint: false,
  variation: false,
  set_id: "83491685-880d-41dd-a4af-47d2b3b17c10",
  set: "ust",
  set_name: "Unstable",
  set_type: "funny",
  set_uri: "https://api.scryfall.com/sets/83491685-880d-41dd-a4af-47d2b3b17c10",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aust&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/ust?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/b4d54442-caca-412d-a716-032eaa587944/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A45f13c9d-cdbe-42c4-9563-cf539fe7e075&unique=prints",
  collector_number: "157",
  digital: false,
  rarity: "uncommon",
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "Matt Dixon",
  artist_ids: ["02e3a0df-c0ac-4eb4-a902-b3bee822f025"],
  illustration_id: "c6c66d87-974f-468a-bc96-b91b17b93856",
  border_color: "silver",
  frame: "2015",
  full_art: false,
  textless: false,
  booster: true,
  story_spotlight: false,
  prices: {
    usd: "0.17",
    usd_foil: "0.40",
    usd_etched: null,
    eur: "0.05",
    eur_foil: "0.48",
    tix: null,
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=439546",
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Robo-&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Robo-&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Robo-",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/product/153183?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Robo-&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Robo-&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
