import { ScryfallCard } from "src";

const Robo: ScryfallCard.Augment = {
  object: "card",
  id: "569f48f9-db8c-458d-b1c8-fed5fd844bfd",
  oracle_id: "8937f17f-f052-416a-b5d4-b91b9f0793c9",
  multiverse_ids: [439504],
  tcgplayer_id: 152663,
  cardmarket_id: 313782,
  name: "Monkey-",
  lang: "en",
  released_at: "2017-12-08",
  uri: "https://api.scryfall.com/cards/569f48f9-db8c-458d-b1c8-fed5fd844bfd",
  scryfall_uri: "https://scryfall.com/card/ust/115/monkey-?utm_source=api",
  layout: "augment",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/5/6/569f48f9-db8c-458d-b1c8-fed5fd844bfd.jpg?1572374080",
    normal: "https://cards.scryfall.io/normal/front/5/6/569f48f9-db8c-458d-b1c8-fed5fd844bfd.jpg?1572374080",
    large: "https://cards.scryfall.io/large/front/5/6/569f48f9-db8c-458d-b1c8-fed5fd844bfd.jpg?1572374080",
    png: "https://cards.scryfall.io/png/front/5/6/569f48f9-db8c-458d-b1c8-fed5fd844bfd.png?1572374080",
    art_crop: "https://cards.scryfall.io/art_crop/front/5/6/569f48f9-db8c-458d-b1c8-fed5fd844bfd.jpg?1572374080",
    border_crop: "https://cards.scryfall.io/border_crop/front/5/6/569f48f9-db8c-458d-b1c8-fed5fd844bfd.jpg?1572374080",
  },
  mana_cost: "",
  cmc: 0.0,
  type_line: "Creature — Monkey",
  oracle_text:
    "Whenever a nontoken creature you control dies,\nAugment {2}{G} ({2}{G}, Reveal this card from your hand: Combine it with target host. Augment only as a sorcery.)",
  power: "+2",
  toughness: "+2",
  colors: ["G"],
  color_indicator: ["G"],
  color_identity: ["G"],
  keywords: ["Augment"],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "not_legal",
    gladiator: "not_legal",
    pioneer: "not_legal",
    explorer: "not_legal",
    modern: "not_legal",
    legacy: "not_legal",
    pauper: "not_legal",
    vintage: "not_legal",
    penny: "not_legal",
    commander: "not_legal",
    oathbreaker: "not_legal",
    brawl: "not_legal",
    historicbrawl: "not_legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "not_legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["paper"],
  reserved: false,
  foil: true,
  nonfoil: true,
  finishes: ["nonfoil", "foil"],
  oversized: false,
  promo: false,
  reprint: false,
  variation: false,
  set_id: "83491685-880d-41dd-a4af-47d2b3b17c10",
  set: "ust",
  set_name: "Unstable",
  set_type: "funny",
  set_uri: "https://api.scryfall.com/sets/83491685-880d-41dd-a4af-47d2b3b17c10",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aust&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/ust?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/569f48f9-db8c-458d-b1c8-fed5fd844bfd/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A8937f17f-f052-416a-b5d4-b91b9f0793c9&unique=prints",
  collector_number: "115",
  digital: false,
  rarity: "uncommon",
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "Andrea Radeck",
  artist_ids: ["2560b932-96b5-4308-9d32-298641ef326e"],
  illustration_id: "1330ebf0-37f0-4072-b020-16a770a4a9a1",
  border_color: "silver",
  frame: "2015",
  full_art: false,
  textless: false,
  booster: true,
  story_spotlight: false,
  prices: {
    usd: "0.15",
    usd_foil: "0.35",
    usd_etched: null,
    eur: "0.10",
    eur_foil: "0.47",
    tix: null,
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=439504",
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Monkey-&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Monkey-&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Monkey-",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/product/152663?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Monkey-&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Monkey-&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
