import { ScryfallCard } from "../../Card";

const FireAndIce_Ja: ScryfallCard.Split = {
  object: "card",
  id: "b1932ef7-c6ff-4708-851c-cec56def4fc2",
  oracle_id: "ae92942b-919c-4ea9-b693-85fcef765d5a",
  multiverse_ids: [457075],
  name: "Fire // Ice",
  lang: "ja",
  released_at: "2018-12-07",
  uri: "https://api.scryfall.com/cards/b1932ef7-c6ff-4708-851c-cec56def4fc2",
  scryfall_uri: "https://scryfall.com/card/uma/225/ja/%E7%81%AB-%E6%B0%B7?utm_source=api",
  layout: "split",
  highres_image: false,
  image_status: "lowres",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/b/1/b1932ef7-c6ff-4708-851c-cec56def4fc2.jpg?1544049342",
    normal: "https://cards.scryfall.io/normal/front/b/1/b1932ef7-c6ff-4708-851c-cec56def4fc2.jpg?1544049342",
    large: "https://cards.scryfall.io/large/front/b/1/b1932ef7-c6ff-4708-851c-cec56def4fc2.jpg?1544049342",
    png: "https://cards.scryfall.io/png/front/b/1/b1932ef7-c6ff-4708-851c-cec56def4fc2.png?1544049342",
    art_crop: "https://cards.scryfall.io/art_crop/front/b/1/b1932ef7-c6ff-4708-851c-cec56def4fc2.jpg?1544049342",
    border_crop: "https://cards.scryfall.io/border_crop/front/b/1/b1932ef7-c6ff-4708-851c-cec56def4fc2.jpg?1544049342",
  },
  mana_cost: "{1}{R} // {1}{U}",
  cmc: 4.0,
  type_line: "Instant // Instant",
  colors: ["R", "U"],
  color_identity: ["R", "U"],
  keywords: [],
  card_faces: [
    {
      object: "card_face",
      name: "Fire",
      printed_name: "火",
      mana_cost: "{1}{R}",
      type_line: "Instant",
      printed_type_line: "インスタント",
      oracle_text: "Fire deals 2 damage divided as you choose among one or two targets.",
      printed_text:
        "クリーチャーやプレイヤーを、１つまたは望む組み合わせで２つ対象とする。火はそれらに、２点のダメージをあなたの好きなように分割して与える。",
      artist: "Dan Scott",
      artist_id: "f852fa13-137e-40f2-bbc1-0f01df09c0e0",
      illustration_id: "511174a2-18dc-4582-9de1-c04871eb77de",
    },
    {
      object: "card_face",
      name: "Ice",
      flavor_name: "",
      printed_name: "氷",
      mana_cost: "{1}{U}",
      type_line: "Instant",
      printed_type_line: "インスタント",
      oracle_text: "Tap target permanent.\nDraw a card.",
      printed_text: "パーマネント１つを対象とし、それをタップする。カードを１枚引く。",
      artist: "Dan Scott",
      artist_id: "f852fa13-137e-40f2-bbc1-0f01df09c0e0",
    },
  ],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "not_legal",
    gladiator: "not_legal",
    pioneer: "not_legal",
    explorer: "not_legal",
    modern: "legal",
    legacy: "legal",
    pauper: "legal",
    vintage: "legal",
    penny: "not_legal",
    commander: "legal",
    oathbreaker: "legal",
    brawl: "not_legal",
    historicbrawl: "not_legal",
    alchemy: "not_legal",
    paupercommander: "legal",
    duel: "legal",
    oldschool: "not_legal",
    premodern: "legal",
    predh: "legal",
  },
  games: ["paper", "mtgo"],
  reserved: false,
  foil: true,
  nonfoil: true,
  finishes: ["nonfoil", "foil"],
  oversized: false,
  promo: false,
  reprint: true,
  variation: false,
  set_id: "2ec77b94-6d47-4891-a480-5d0b4e5c9372",
  set: "uma",
  set_name: "Ultimate Masters",
  set_type: "masters",
  set_uri: "https://api.scryfall.com/sets/2ec77b94-6d47-4891-a480-5d0b4e5c9372",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Auma&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/uma?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/b1932ef7-c6ff-4708-851c-cec56def4fc2/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Aae92942b-919c-4ea9-b693-85fcef765d5a&unique=prints",
  collector_number: "225",
  digital: false,
  rarity: "common",
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "Dan Scott",
  artist_ids: ["f852fa13-137e-40f2-bbc1-0f01df09c0e0"],
  illustration_id: "511174a2-18dc-4582-9de1-c04871eb77de",
  border_color: "black",
  frame: "2015",
  full_art: false,
  textless: false,
  booster: true,
  story_spotlight: false,
  edhrec_rank: 8855,
  penny_rank: 469,
  prices: {
    usd: null,
    usd_foil: null,
    usd_etched: null,
    eur: null,
    eur_foil: null,
    tix: null,
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=457075&printed=true",
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Fire+%2F%2F+Ice&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Fire+%2F%2F+Ice&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Fire+%2F%2F+Ice",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/search/magic/product?productLineName=magic&q=Fire+%2F%2F+Ice&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall&view=grid",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Fire+%2F%2F+Ice&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Fire+%2F%2F+Ice&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
