import { ScryfallCard } from "src";

const Bask: ScryfallCard.Scheme = {
  object: "card",
  id: "ca36efdd-c60c-412c-9fd5-5e6b97d2f9cd",
  oracle_id: "bf77c996-df58-45d8-bce7-6de3e4fa20da",
  multiverse_ids: [212614],
  tcgplayer_id: 37150,
  cardmarket_id: 240591,
  name: "I Bask in Your Silent Awe",
  lang: "en",
  released_at: "2010-06-18",
  uri: "https://api.scryfall.com/cards/ca36efdd-c60c-412c-9fd5-5e6b97d2f9cd",
  scryfall_uri: "https://scryfall.com/card/oarc/15%E2%98%85/i-bask-in-your-silent-awe?utm_source=api",
  layout: "scheme",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/c/a/ca36efdd-c60c-412c-9fd5-5e6b97d2f9cd.jpg?1562252736",
    normal: "https://cards.scryfall.io/normal/front/c/a/ca36efdd-c60c-412c-9fd5-5e6b97d2f9cd.jpg?1562252736",
    large: "https://cards.scryfall.io/large/front/c/a/ca36efdd-c60c-412c-9fd5-5e6b97d2f9cd.jpg?1562252736",
    png: "https://cards.scryfall.io/png/front/c/a/ca36efdd-c60c-412c-9fd5-5e6b97d2f9cd.png?1562252736",
    art_crop: "https://cards.scryfall.io/art_crop/front/c/a/ca36efdd-c60c-412c-9fd5-5e6b97d2f9cd.jpg?1562252736",
    border_crop: "https://cards.scryfall.io/border_crop/front/c/a/ca36efdd-c60c-412c-9fd5-5e6b97d2f9cd.jpg?1562252736",
  },
  mana_cost: "",
  cmc: 0.0,
  type_line: "Ongoing Scheme",
  oracle_text:
    "(An ongoing scheme remains face up until it's abandoned.)\nEach opponent can't cast more than one spell each turn.\nAt the beginning of your upkeep, if no opponent cast a spell since your last turn ended, abandon this scheme.",
  colors: [],
  color_identity: [],
  keywords: [],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "not_legal",
    gladiator: "not_legal",
    pioneer: "not_legal",
    explorer: "not_legal",
    modern: "not_legal",
    legacy: "not_legal",
    pauper: "not_legal",
    vintage: "not_legal",
    penny: "not_legal",
    commander: "not_legal",
    oathbreaker: "not_legal",
    brawl: "not_legal",
    historicbrawl: "not_legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "not_legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["paper"],
  reserved: false,
  foil: false,
  nonfoil: true,
  finishes: ["nonfoil"],
  oversized: true,
  promo: false,
  reprint: false,
  variation: false,
  set_id: "238beedf-1d4d-475f-a980-527ba2f55dc6",
  set: "oarc",
  set_name: "Archenemy Schemes",
  set_type: "archenemy",
  set_uri: "https://api.scryfall.com/sets/238beedf-1d4d-475f-a980-527ba2f55dc6",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aoarc&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/oarc?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/ca36efdd-c60c-412c-9fd5-5e6b97d2f9cd/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Abf77c996-df58-45d8-bce7-6de3e4fa20da&unique=prints",
  collector_number: "15★",
  digital: false,
  rarity: "common",
  card_back_id: "1b2396d4-9048-439d-96bd-354288518841",
  artist: "Wayne Reynolds",
  artist_ids: ["afc47cec-3ccc-404e-a8c6-4d83dd504271"],
  illustration_id: "9d0e8641-fc60-4031-818b-7d27bdd673dd",
  border_color: "black",
  frame: "2003",
  full_art: false,
  textless: false,
  booster: false,
  story_spotlight: false,
  prices: {
    usd: "3.47",
    usd_foil: null,
    usd_etched: null,
    eur: "0.05",
    eur_foil: null,
    tix: null,
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=212614",
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=I+Bask+in+Your+Silent+Awe&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=I+Bask+in+Your+Silent+Awe&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=I+Bask+in+Your+Silent+Awe",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/product/37150?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=I+Bask+in+Your+Silent+Awe&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=I+Bask+in+Your+Silent+Awe&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
