import { ScryfallCard } from "src";

const Esika: TestCard<ScryfallCard.ModalDfc> = {
  object: "card",
  id: "f6cd7465-9dd0-473c-ac5e-dd9e2f22f5f6",
  oracle_id: "92023a5d-a143-4950-a71b-d736e6b8e959",
  multiverse_ids: [503781, 503782],
  mtgo_id: 87673,
  arena_id: 75212,
  tcgplayer_id: 230163,
  cardmarket_id: 530332,
  name: "Esika, God of the Tree // The Prismatic Bridge",
  lang: "en",
  released_at: "2021-02-05",
  uri: "https://api.scryfall.com/cards/f6cd7465-9dd0-473c-ac5e-dd9e2f22f5f6",
  scryfall_uri: "https://scryfall.com/card/khm/168/esika-god-of-the-tree-the-prismatic-bridge?utm_source=api",
  layout: "modal_dfc",
  highres_image: true,
  image_status: "highres_scan",
  cmc: 3.0,
  type_line: "Legendary Creature — God // Legendary Enchantment",
  color_identity: ["B", "G", "R", "U", "W"],
  keywords: ["Vigilance"],
  produced_mana: ["B", "G", "R", "U", "W"],
  card_faces: [
    {
      object: "card_face",
      name: "Esika, God of the Tree",
      mana_cost: "{1}{G}{G}",
      type_line: "Legendary Creature — God",
      oracle_text:
        'Vigilance\n{T}: Add one mana of any color.\nOther legendary creatures you control have vigilance and "{T}: Add one mana of any color."',
      colors: ["G"],
      power: "1",
      toughness: "4",
      flavor_text: '"I know this world, from canopy to roots."',
      artist: "Johannes Voss",
      artist_id: "3593dd7e-c547-4a32-81cd-7da725f60118",
      illustration_id: "b02e8c7b-b733-4d3b-9d71-7a48c4d2e713",
      image_uris: {
        small: "https://cards.scryfall.io/small/front/f/6/f6cd7465-9dd0-473c-ac5e-dd9e2f22f5f6.jpg?1631050188",
        normal: "https://cards.scryfall.io/normal/front/f/6/f6cd7465-9dd0-473c-ac5e-dd9e2f22f5f6.jpg?1631050188",
        large: "https://cards.scryfall.io/large/front/f/6/f6cd7465-9dd0-473c-ac5e-dd9e2f22f5f6.jpg?1631050188",
        png: "https://cards.scryfall.io/png/front/f/6/f6cd7465-9dd0-473c-ac5e-dd9e2f22f5f6.png?1631050188",
        art_crop: "https://cards.scryfall.io/art_crop/front/f/6/f6cd7465-9dd0-473c-ac5e-dd9e2f22f5f6.jpg?1631050188",
        border_crop:
          "https://cards.scryfall.io/border_crop/front/f/6/f6cd7465-9dd0-473c-ac5e-dd9e2f22f5f6.jpg?1631050188",
      },
    },
    {
      object: "card_face",
      name: "The Prismatic Bridge",
      flavor_name: "",
      mana_cost: "{W}{U}{B}{R}{G}",
      type_line: "Legendary Enchantment",
      oracle_text:
        "At the beginning of your upkeep, reveal cards from the top of your library until you reveal a creature or planeswalker card. Put that card onto the battlefield and the rest on the bottom of your library in a random order.",
      colors: ["B", "G", "R", "U", "W"],
      flavor_text: "Starnheim awaits.",
      artist: "Johannes Voss",
      artist_id: "3593dd7e-c547-4a32-81cd-7da725f60118",
      illustration_id: "959283a3-5d90-4e9b-95ce-abc0ab93f75c",
      image_uris: {
        small: "https://cards.scryfall.io/small/back/f/6/f6cd7465-9dd0-473c-ac5e-dd9e2f22f5f6.jpg?1631050188",
        normal: "https://cards.scryfall.io/normal/back/f/6/f6cd7465-9dd0-473c-ac5e-dd9e2f22f5f6.jpg?1631050188",
        large: "https://cards.scryfall.io/large/back/f/6/f6cd7465-9dd0-473c-ac5e-dd9e2f22f5f6.jpg?1631050188",
        png: "https://cards.scryfall.io/png/back/f/6/f6cd7465-9dd0-473c-ac5e-dd9e2f22f5f6.png?1631050188",
        art_crop: "https://cards.scryfall.io/art_crop/back/f/6/f6cd7465-9dd0-473c-ac5e-dd9e2f22f5f6.jpg?1631050188",
        border_crop:
          "https://cards.scryfall.io/border_crop/back/f/6/f6cd7465-9dd0-473c-ac5e-dd9e2f22f5f6.jpg?1631050188",
      },
    },
  ],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "legal",
    gladiator: "legal",
    pioneer: "legal",
    explorer: "legal",
    modern: "legal",
    legacy: "legal",
    pauper: "not_legal",
    vintage: "legal",
    penny: "not_legal",
    commander: "legal",
    oathbreaker: "legal",
    brawl: "not_legal",
    historicbrawl: "legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["arena", "paper", "mtgo"],
  reserved: false,
  foil: true,
  nonfoil: true,
  finishes: ["nonfoil", "foil"],
  oversized: false,
  promo: false,
  reprint: false,
  variation: false,
  set_id: "43057fad-b1c1-437f-bc48-0045bce6d8c9",
  set: "khm",
  set_name: "Kaldheim",
  set_type: "expansion",
  set_uri: "https://api.scryfall.com/sets/43057fad-b1c1-437f-bc48-0045bce6d8c9",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Akhm&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/khm?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/f6cd7465-9dd0-473c-ac5e-dd9e2f22f5f6/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A92023a5d-a143-4950-a71b-d736e6b8e959&unique=prints",
  collector_number: "168",
  digital: false,
  rarity: "mythic",
  artist: "Johannes Voss",
  artist_ids: ["3593dd7e-c547-4a32-81cd-7da725f60118"],
  border_color: "black",
  frame: "2015",
  frame_effects: ["legendary"],
  security_stamp: "oval",
  full_art: false,
  textless: false,
  booster: true,
  story_spotlight: false,
  edhrec_rank: 1565,
  preview: {
    source: "ChannelFireball",
    source_uri:
      "https://strategy.channelfireball.com/all-strategy/mtg/kaldheim-card-preview-esika-god-of-the-tree-the-prismatic-bridge/",
    previewed_at: "2021-01-08",
  },
  prices: {
    usd: "10.06",
    usd_foil: "12.10",
    usd_etched: null,
    eur: "12.54",
    eur_foil: "12.00",
    tix: "0.54",
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=503781",
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Esika%2C+God+of+the+Tree+%2F%2F+The+Prismatic+Bridge&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Esika%2C+God+of+the+Tree+%2F%2F+The+Prismatic+Bridge&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Esika%2C+God+of+the+Tree",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/product/230163?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Esika%2C+God+of+the+Tree&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards/87673?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};

const Esika_Unknown: ScryfallCard.Blob = Esika;
