import { ScryfallCard } from "../../../Card";

const Kiora: ScryfallCard.Emblem = {
  object: "card",
  id: "e45f7850-2ebb-4530-9859-f87b4e0e27be",
  oracle_id: "1a7523ff-8683-4187-bea7-edee70392791",
  multiverse_ids: [],
  tcgplayer_id: 79194,
  name: "Kiora, the Crashing Wave Emblem",
  lang: "en",
  released_at: "2014-02-07",
  uri: "https://api.scryfall.com/cards/e45f7850-2ebb-4530-9859-f87b4e0e27be",
  scryfall_uri: "https://scryfall.com/card/tbng/11/kiora-the-crashing-wave-emblem?utm_source=api",
  layout: "emblem",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/e/4/e45f7850-2ebb-4530-9859-f87b4e0e27be.jpg?1562636877",
    normal: "https://cards.scryfall.io/normal/front/e/4/e45f7850-2ebb-4530-9859-f87b4e0e27be.jpg?1562636877",
    large: "https://cards.scryfall.io/large/front/e/4/e45f7850-2ebb-4530-9859-f87b4e0e27be.jpg?1562636877",
    png: "https://cards.scryfall.io/png/front/e/4/e45f7850-2ebb-4530-9859-f87b4e0e27be.png?1562636877",
    art_crop: "https://cards.scryfall.io/art_crop/front/e/4/e45f7850-2ebb-4530-9859-f87b4e0e27be.jpg?1562636877",
    border_crop: "https://cards.scryfall.io/border_crop/front/e/4/e45f7850-2ebb-4530-9859-f87b4e0e27be.jpg?1562636877",
  },
  mana_cost: "",
  cmc: 0.0,
  type_line: "Emblem — Kiora",
  oracle_text: "At the beginning of your end step, create a 9/9 blue Kraken creature token.",
  colors: [],
  color_identity: [],
  keywords: [],
  all_parts: [
    {
      object: "related_card",
      id: "e45f7850-2ebb-4530-9859-f87b4e0e27be",
      component: "combo_piece",
      name: "Kiora, the Crashing Wave Emblem",
      type_line: "Emblem — Kiora",
      uri: "https://api.scryfall.com/cards/e45f7850-2ebb-4530-9859-f87b4e0e27be",
    },
    {
      object: "related_card",
      id: "f77ac7fa-718d-425f-a0aa-2f8e2bfc0950",
      component: "combo_piece",
      name: "Kiora, the Crashing Wave",
      type_line: "Legendary Planeswalker — Kiora",
      uri: "https://api.scryfall.com/cards/f77ac7fa-718d-425f-a0aa-2f8e2bfc0950",
    },
  ],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "not_legal",
    gladiator: "not_legal",
    pioneer: "not_legal",
    explorer: "not_legal",
    modern: "not_legal",
    legacy: "not_legal",
    pauper: "not_legal",
    vintage: "not_legal",
    penny: "not_legal",
    commander: "not_legal",
    oathbreaker: "not_legal",
    brawl: "not_legal",
    historicbrawl: "not_legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "not_legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["paper"],
  reserved: false,
  foil: false,
  nonfoil: true,
  finishes: ["nonfoil"],
  oversized: false,
  promo: false,
  reprint: false,
  variation: false,
  set_id: "81dd6941-9598-43ab-abd7-fd5f2b71b171",
  set: "tbng",
  set_name: "Born of the Gods Tokens",
  set_type: "token",
  set_uri: "https://api.scryfall.com/sets/81dd6941-9598-43ab-abd7-fd5f2b71b171",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Atbng&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/tbng?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/e45f7850-2ebb-4530-9859-f87b4e0e27be/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A1a7523ff-8683-4187-bea7-edee70392791&unique=prints",
  collector_number: "11",
  digital: false,
  rarity: "common",
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "Scott M. Fischer",
  artist_ids: ["23b0cf43-3e43-44c6-8329-96446eca5bce"],
  illustration_id: "90f55c9a-ee1e-4e05-bf74-e4fcf8c04d83",
  border_color: "black",
  frame: "2003",
  full_art: false,
  textless: false,
  booster: true,
  story_spotlight: false,
  promo_types: ["setpromo"],
  prices: {
    usd: "4.47",
    usd_foil: null,
    usd_etched: null,
    eur: null,
    eur_foil: null,
    tix: null,
  },
  related_uris: {
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Kiora%2C+the+Crashing+Wave+Emblem&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Kiora%2C+the+Crashing+Wave+Emblem&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Kiora%2C+the+Crashing+Wave+Emblem",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/product/79194?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Kiora%2C+the+Crashing+Wave+Emblem&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Kiora%2C+the+Crashing+Wave+Emblem&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
