import { ScryfallCard } from "src";

// Flip card
const AkkiLavarunner: TestCard<ScryfallCard.Flip> = {
  object: "card",
  id: "6ee6cd34-c117-4d7e-97d1-8f8464bfaac8",
  oracle_id: "47795817-73e5-4af6-bd1e-d69b193e8e9e",
  multiverse_ids: [78694],
  mtgo_id: 21237,
  mtgo_foil_id: 21238,
  tcgplayer_id: 11938,
  cardmarket_id: 11957,
  name: "Akki Lavarunner // Tok-Tok, Volcano Born",
  lang: "en",
  released_at: "2004-10-01",
  uri: "https://api.scryfall.com/cards/6ee6cd34-c117-4d7e-97d1-8f8464bfaac8",
  scryfall_uri: "https://scryfall.com/card/chk/153/akki-lavarunner-tok-tok-volcano-born?utm_source=api",
  layout: "flip",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/6/e/6ee6cd34-c117-4d7e-97d1-8f8464bfaac8.jpg?1562761096",
    normal: "https://cards.scryfall.io/normal/front/6/e/6ee6cd34-c117-4d7e-97d1-8f8464bfaac8.jpg?1562761096",
    large: "https://cards.scryfall.io/large/front/6/e/6ee6cd34-c117-4d7e-97d1-8f8464bfaac8.jpg?1562761096",
    png: "https://cards.scryfall.io/png/front/6/e/6ee6cd34-c117-4d7e-97d1-8f8464bfaac8.png?1562761096",
    art_crop: "https://cards.scryfall.io/art_crop/front/6/e/6ee6cd34-c117-4d7e-97d1-8f8464bfaac8.jpg?1562761096",
    border_crop: "https://cards.scryfall.io/border_crop/front/6/e/6ee6cd34-c117-4d7e-97d1-8f8464bfaac8.jpg?1562761096",
  },
  mana_cost: "{3}{R}",
  cmc: 4.0,
  type_line: "Creature — Goblin Warrior // Legendary Creature — Goblin Shaman",
  power: "1",
  toughness: "1",
  colors: ["R"],
  color_identity: ["R"],
  keywords: ["Protection", "Haste"],
  card_faces: [
    {
      object: "card_face",
      name: "Akki Lavarunner",
      mana_cost: "{3}{R}",
      type_line: "Creature — Goblin Warrior",
      oracle_text: "Haste\nWhenever Akki Lavarunner deals damage to an opponent, flip it.",
      power: "1",
      toughness: "1",
      artist: "Matt Cavotta",
      artist_id: "2e6a0611-9411-4ba4-98e3-c0e18cbf9f83",
      illustration_id: "54705304-6aeb-4722-9a17-9006db12b939",
    },
    {
      object: "card_face",
      name: "Tok-Tok, Volcano Born",
      flavor_name: "",
      mana_cost: "",
      type_line: "Legendary Creature — Goblin Shaman",
      oracle_text:
        "Protection from red\nIf a red source would deal damage to a player, it deals that much damage plus 1 to that player instead.",
      power: "2",
      toughness: "2",
      artist: "Matt Cavotta",
      artist_id: "2e6a0611-9411-4ba4-98e3-c0e18cbf9f83",
    },
  ],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "not_legal",
    gladiator: "not_legal",
    pioneer: "not_legal",
    explorer: "not_legal",
    modern: "legal",
    legacy: "legal",
    pauper: "not_legal",
    vintage: "legal",
    penny: "legal",
    commander: "legal",
    oathbreaker: "legal",
    brawl: "not_legal",
    historicbrawl: "not_legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "legal",
  },
  games: ["paper", "mtgo"],
  reserved: false,
  foil: true,
  nonfoil: true,
  finishes: ["nonfoil", "foil"],
  oversized: false,
  promo: false,
  reprint: false,
  variation: false,
  set_id: "6183d21f-a0af-4118-ba58-aca1d8719c01",
  set: "chk",
  set_name: "Champions of Kamigawa",
  set_type: "expansion",
  set_uri: "https://api.scryfall.com/sets/6183d21f-a0af-4118-ba58-aca1d8719c01",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Achk&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/chk?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/6ee6cd34-c117-4d7e-97d1-8f8464bfaac8/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A47795817-73e5-4af6-bd1e-d69b193e8e9e&unique=prints",
  collector_number: "153",
  digital: false,
  rarity: "rare",
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "Matt Cavotta",
  artist_ids: ["2e6a0611-9411-4ba4-98e3-c0e18cbf9f83"],
  illustration_id: "54705304-6aeb-4722-9a17-9006db12b939",
  border_color: "black",
  frame: "2003",
  full_art: false,
  textless: false,
  booster: true,
  story_spotlight: false,
  edhrec_rank: 14721,
  penny_rank: 13983,
  prices: {
    usd: "0.46",
    usd_foil: "5.47",
    usd_etched: null,
    eur: "0.25",
    eur_foil: "3.85",
    tix: "0.02",
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=78694",
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Akki+Lavarunner+%2F%2F+Tok-Tok%2C+Volcano+Born&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Akki+Lavarunner+%2F%2F+Tok-Tok%2C+Volcano+Born&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Akki+Lavarunner",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/product/11938?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Akki+Lavarunner&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards/21237?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};

const AkkiLavarunner_Unknown: ScryfallCard.Blob = AkkiLavarunner;
