import { ScryfallCard } from "../../../../Card";

// French vanilla creature
const MantisRider: ScryfallCard.Normal = {
  object: "card",
  id: "82d5ce46-7118-4ede-ba1d-c387e7ce16e7",
  oracle_id: "5c1a0a7a-dea4-4b8e-b9c0-8c19942a01ef",
  multiverse_ids: [386589],
  mtgo_id: 54434,
  mtgo_foil_id: 54435,
  tcgplayer_id: 92974,
  cardmarket_id: 269338,
  name: "Mantis Rider",
  lang: "en",
  released_at: "2014-09-26",
  uri: "https://api.scryfall.com/cards/82d5ce46-7118-4ede-ba1d-c387e7ce16e7",
  scryfall_uri: "https://scryfall.com/card/ktk/184/mantis-rider?utm_source=api",
  layout: "normal",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/8/2/82d5ce46-7118-4ede-ba1d-c387e7ce16e7.jpg?1562789458",
    normal: "https://cards.scryfall.io/normal/front/8/2/82d5ce46-7118-4ede-ba1d-c387e7ce16e7.jpg?1562789458",
    large: "https://cards.scryfall.io/large/front/8/2/82d5ce46-7118-4ede-ba1d-c387e7ce16e7.jpg?1562789458",
    png: "https://cards.scryfall.io/png/front/8/2/82d5ce46-7118-4ede-ba1d-c387e7ce16e7.png?1562789458",
    art_crop: "https://cards.scryfall.io/art_crop/front/8/2/82d5ce46-7118-4ede-ba1d-c387e7ce16e7.jpg?1562789458",
    border_crop: "https://cards.scryfall.io/border_crop/front/8/2/82d5ce46-7118-4ede-ba1d-c387e7ce16e7.jpg?1562789458",
  },
  mana_cost: "{U}{R}{W}",
  cmc: 3.0,
  type_line: "Creature — Human Monk",
  oracle_text: "Flying, vigilance, haste",
  power: "3",
  toughness: "3",
  colors: ["R", "U", "W"],
  color_identity: ["R", "U", "W"],
  keywords: ["Flying", "Vigilance", "Haste"],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "not_legal",
    gladiator: "not_legal",
    pioneer: "legal",
    explorer: "not_legal",
    modern: "legal",
    legacy: "legal",
    pauper: "not_legal",
    vintage: "legal",
    penny: "legal",
    commander: "legal",
    oathbreaker: "legal",
    brawl: "not_legal",
    historicbrawl: "not_legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["paper", "mtgo"],
  reserved: false,
  foil: true,
  nonfoil: true,
  finishes: ["nonfoil", "foil"],
  oversized: false,
  promo: false,
  reprint: false,
  variation: false,
  set_id: "6c7a715c-ded9-449e-89b0-c665773e9c3c",
  set: "ktk",
  set_name: "Khans of Tarkir",
  set_type: "expansion",
  set_uri: "https://api.scryfall.com/sets/6c7a715c-ded9-449e-89b0-c665773e9c3c",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aktk&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/ktk?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/82d5ce46-7118-4ede-ba1d-c387e7ce16e7/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A5c1a0a7a-dea4-4b8e-b9c0-8c19942a01ef&unique=prints",
  collector_number: "184",
  digital: false,
  rarity: "rare",
  watermark: "jeskai",
  flavor_text:
    "Mantis riders know their mounts owe them no allegiance. Even a mantis ridden for years would consume a rider who loses focus for only a moment.",
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "Johann Bodin",
  artist_ids: ["d92e2dd9-9ef6-43f6-81f8-df87f9066983"],
  illustration_id: "1f010139-e53f-42e5-ac18-e21cb5225f91",
  border_color: "black",
  frame: "2015",
  security_stamp: "oval",
  full_art: false,
  textless: false,
  booster: true,
  story_spotlight: false,
  edhrec_rank: 11290,
  penny_rank: 1793,
  prices: {
    usd: "0.37",
    usd_foil: "3.51",
    usd_etched: null,
    eur: "0.37",
    eur_foil: "1.90",
    tix: "0.02",
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=386589",
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Mantis+Rider&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Mantis+Rider&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Mantis+Rider",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/product/92974?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Mantis+Rider&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards/54434?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
