const AeromoebaSignedNoImage = {
  object: "card",
  id: "8fc79219-c983-47e2-9ca8-2aaa96828e3b",
  oracle_id: "9492d339-afa4-4d06-af31-731110927baa",
  multiverse_ids: [],
  name: "Aeromoeba // Aeromoeba",
  lang: "en",
  released_at: "2021-06-18",
  uri: "https://api.scryfall.com/cards/8fc79219-c983-47e2-9ca8-2aaa96828e3b",
  scryfall_uri: "https://scryfall.com/card/amh2/11s/aeromoeba-aeromoeba?utm_source=api",
  layout: "art_series",
  highres_image: false,
  image_status: "missing",
  cmc: 0.0,
  type_line: "Card // Card",
  color_identity: [],
  keywords: [],
  card_faces: [
    {
      object: "card_face",
      name: "Aeromoeba",
      mana_cost: "",
      type_line: "Card",
      oracle_text: "",
      colors: [],
      artist: "Victor Adame Minguez",
      artist_id: "bd8f7368-5b10-4554-b6b8-d052c6aca89f",
      illustration_id: "d0e0091d-16ad-4557-99f7-092c54d0459e",
    },
    {
      object: "card_face",
      name: "Aeromoeba",
      flavor_name: "",
      mana_cost: "",
      type_line: "Card",
      oracle_text: "",
      colors: [],
      artist: "Victor Adame Minguez",
      artist_id: "bd8f7368-5b10-4554-b6b8-d052c6aca89f",
    },
  ],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "not_legal",
    gladiator: "not_legal",
    pioneer: "not_legal",
    explorer: "not_legal",
    modern: "not_legal",
    legacy: "not_legal",
    pauper: "not_legal",
    vintage: "not_legal",
    penny: "not_legal",
    commander: "not_legal",
    oathbreaker: "not_legal",
    brawl: "not_legal",
    historicbrawl: "not_legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "not_legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["paper"],
  reserved: false,
  foil: false,
  nonfoil: true,
  finishes: ["nonfoil"],
  oversized: false,
  promo: false,
  reprint: false,
  variation: false,
  set_id: "95671546-fd82-43e2-966f-eba5968f629b",
  set: "amh2",
  set_name: "Modern Horizons 2 Art Series",
  set_type: "memorabilia",
  set_uri: "https://api.scryfall.com/sets/95671546-fd82-43e2-966f-eba5968f629b",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aamh2&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/amh2?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/8fc79219-c983-47e2-9ca8-2aaa96828e3b/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A9492d339-afa4-4d06-af31-731110927baa&unique=prints",
  collector_number: "11s",
  digital: false,
  rarity: "common",
  artist: "Victor Adame Minguez",
  artist_ids: ["bd8f7368-5b10-4554-b6b8-d052c6aca89f"],
  border_color: "borderless",
  frame: "2015",
  full_art: false,
  textless: false,
  booster: false,
  story_spotlight: false,
  promo_types: ["stamped"],
  prices: {
    usd: null,
    usd_foil: null,
    usd_etched: null,
    eur: null,
    eur_foil: null,
    tix: null,
  },
  related_uris: {
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Aeromoeba+%2F%2F+Aeromoeba&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Aeromoeba+%2F%2F+Aeromoeba&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Aeromoeba",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/search/magic/product?productLineName=magic&q=Aeromoeba&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall&view=grid",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Aeromoeba&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Aeromoeba&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
