import { ScryfallCard } from "../../../Card";

const Kerblam: ScryfallCard.Planar = {
  object: "card",
  id: "4c46b6c1-0c84-4bd3-b317-9b8191ad937e",
  oracle_id: "71bff56b-733c-4d74-9e0c-85371a8b3787",
  multiverse_ids: [],
  name: "Kerblam! Warehouse",
  lang: "en",
  released_at: "2023-10-13",
  uri: "https://api.scryfall.com/cards/4c46b6c1-0c84-4bd3-b317-9b8191ad937e",
  scryfall_uri: "https://scryfall.com/card/who/586/kerblam!-warehouse?utm_source=api",
  layout: "planar",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/4/c/4c46b6c1-0c84-4bd3-b317-9b8191ad937e.jpg?1696637769",
    normal: "https://cards.scryfall.io/normal/front/4/c/4c46b6c1-0c84-4bd3-b317-9b8191ad937e.jpg?1696637769",
    large: "https://cards.scryfall.io/large/front/4/c/4c46b6c1-0c84-4bd3-b317-9b8191ad937e.jpg?1696637769",
    png: "https://cards.scryfall.io/png/front/4/c/4c46b6c1-0c84-4bd3-b317-9b8191ad937e.png?1696637769",
    art_crop: "https://cards.scryfall.io/art_crop/front/4/c/4c46b6c1-0c84-4bd3-b317-9b8191ad937e.jpg?1696637769",
    border_crop: "https://cards.scryfall.io/border_crop/front/4/c/4c46b6c1-0c84-4bd3-b317-9b8191ad937e.jpg?1696637769",
  },
  mana_cost: "",
  cmc: 0.0,
  type_line: "Plane — Kandoka",
  oracle_text:
    'Whenever one or more creatures you control deal combat damage to a player, create a Treasure token.\nWhenever chaos ensues, until your next turn, noncreature artifacts you control gain "{T}, Sacrifice this artifact: Flip a coin. If you win the flip, this artifact deals 3 damage to any target."',
  colors: [],
  color_identity: [],
  keywords: ["Treasure"],
  all_parts: [
    {
      object: "related_card",
      id: "77825935-2f71-4bd1-8ec7-9e8be26853c0",
      component: "token",
      name: "Treasure",
      type_line: "Token Artifact — Treasure",
      uri: "https://api.scryfall.com/cards/77825935-2f71-4bd1-8ec7-9e8be26853c0",
    },
    {
      object: "related_card",
      id: "4c46b6c1-0c84-4bd3-b317-9b8191ad937e",
      component: "combo_piece",
      name: "Kerblam! Warehouse",
      type_line: "Plane — Kandoka",
      uri: "https://api.scryfall.com/cards/4c46b6c1-0c84-4bd3-b317-9b8191ad937e",
    },
  ],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "not_legal",
    gladiator: "not_legal",
    pioneer: "not_legal",
    explorer: "not_legal",
    modern: "not_legal",
    legacy: "not_legal",
    pauper: "not_legal",
    vintage: "not_legal",
    penny: "not_legal",
    commander: "not_legal",
    oathbreaker: "not_legal",
    brawl: "not_legal",
    historicbrawl: "not_legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "not_legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["paper"],
  reserved: false,
  foil: false,
  nonfoil: true,
  finishes: ["nonfoil"],
  oversized: true,
  promo: false,
  reprint: false,
  variation: false,
  set_id: "efdfdd99-cee7-4c11-a5e9-03d60f88bdd6",
  set: "who",
  set_name: "Doctor Who",
  set_type: "commander",
  set_uri: "https://api.scryfall.com/sets/efdfdd99-cee7-4c11-a5e9-03d60f88bdd6",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Awho&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/who?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/4c46b6c1-0c84-4bd3-b317-9b8191ad937e/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A71bff56b-733c-4d74-9e0c-85371a8b3787&unique=prints",
  collector_number: "586",
  digital: false,
  rarity: "common",
  card_back_id: "7840c131-f96b-4700-9347-2215c43156e6",
  artist: "David Auden Nash",
  artist_ids: ["092827e0-03f2-4e73-852e-d95eba0fef20"],
  illustration_id: "a68c2690-56e5-4f3d-a495-7305f394e4df",
  border_color: "black",
  frame: "2015",
  security_stamp: "triangle",
  full_art: false,
  textless: false,
  booster: false,
  story_spotlight: false,
  prices: {
    usd: null,
    usd_foil: null,
    usd_etched: null,
    eur: null,
    eur_foil: null,
    tix: null,
  },
  related_uris: {
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Kerblam%21+Warehouse&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Kerblam%21+Warehouse&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Kerblam%21+Warehouse",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/search/magic/product?productLineName=magic&q=Kerblam%21+Warehouse&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall&view=grid",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Kerblam%21+Warehouse&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Kerblam%21+Warehouse&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
