import { ScryfallCard } from "src";

const LydariElephant: ScryfallCard.Normal = {
  object: "card",
  id: "fc34ce52-f917-4e97-a372-f9d18b8ea1fc",
  oracle_id: "af0b1bfd-9b19-4ea8-9a53-8c663d8e55ed",
  multiverse_ids: [],
  name: "Lydari Elephant",
  lang: "ja",
  released_at: "2001-06-28",
  uri: "https://api.scryfall.com/cards/fc34ce52-f917-4e97-a372-f9d18b8ea1fc",
  scryfall_uri: "https://scryfall.com/card/psdg/6/ja/lydari-elephant?utm_source=api",
  layout: "normal",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/f/c/fc34ce52-f917-4e97-a372-f9d18b8ea1fc.jpg?1626969057",
    normal: "https://cards.scryfall.io/normal/front/f/c/fc34ce52-f917-4e97-a372-f9d18b8ea1fc.jpg?1626969057",
    large: "https://cards.scryfall.io/large/front/f/c/fc34ce52-f917-4e97-a372-f9d18b8ea1fc.jpg?1626969057",
    png: "https://cards.scryfall.io/png/front/f/c/fc34ce52-f917-4e97-a372-f9d18b8ea1fc.png?1626969057",
    art_crop: "https://cards.scryfall.io/art_crop/front/f/c/fc34ce52-f917-4e97-a372-f9d18b8ea1fc.jpg?1626969057",
    border_crop: "https://cards.scryfall.io/border_crop/front/f/c/fc34ce52-f917-4e97-a372-f9d18b8ea1fc.jpg?1626969057",
  },
  mana_cost: "{4}{G}",
  cmc: 5.0,
  type_line: "Creature — Elephant",
  oracle_text:
    "As Lydari Elephant enters the battlefield, choose two numbers from 3 to 7 at random. Lydari Elephant's power is equal to the first number chosen and its toughness equal to the second number chosen.",
  power: "*",
  toughness: "*",
  colors: ["G"],
  color_identity: ["G"],
  keywords: [],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "not_legal",
    gladiator: "not_legal",
    pioneer: "not_legal",
    explorer: "not_legal",
    modern: "not_legal",
    legacy: "not_legal",
    pauper: "not_legal",
    vintage: "not_legal",
    penny: "not_legal",
    commander: "not_legal",
    oathbreaker: "not_legal",
    brawl: "not_legal",
    historicbrawl: "not_legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "not_legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["sega"],
  reserved: false,
  foil: false,
  nonfoil: true,
  finishes: ["nonfoil"],
  oversized: false,
  promo: false,
  reprint: false,
  variation: false,
  set_id: "e8099914-89d5-4b89-8930-9b68d0c31916",
  set: "psdg",
  set_name: "Sega Dreamcast Cards",
  set_type: "box",
  set_uri: "https://api.scryfall.com/sets/e8099914-89d5-4b89-8930-9b68d0c31916",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Apsdg&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/psdg?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/fc34ce52-f917-4e97-a372-f9d18b8ea1fc/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Aaf0b1bfd-9b19-4ea8-9a53-8c663d8e55ed&unique=prints",
  collector_number: "6",
  digital: true,
  rarity: "rare",
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "Heather Hudson",
  artist_ids: ["4441fe52-9e41-40c1-9b74-8510426279ab"],
  illustration_id: "0b0ce204-0cf4-42ed-8097-ab653b0fc2fa",
  border_color: "white",
  frame: "1997",
  full_art: false,
  textless: false,
  booster: false,
  story_spotlight: false,
  prices: {
    usd: null,
    usd_foil: null,
    usd_etched: null,
    eur: null,
    eur_foil: null,
    tix: null,
  },
  related_uris: {
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Lydari+Elephant&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Lydari+Elephant&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Lydari+Elephant",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/search/magic/product?productLineName=magic&q=Lydari+Elephant&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall&view=grid",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Lydari+Elephant&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Lydari+Elephant&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
