import { ScryfallCard } from "src";

const BreakingAndEntering: TestCard<ScryfallCard.Split> = {
  object: "card",
  id: "66724f4e-59dd-4c70-b09b-49947320e6d1",
  oracle_id: "043370fd-9cfe-47ce-8019-e915cee1ae95",
  multiverse_ids: [369009],
  mtgo_id: 48526,
  tcgplayer_id: 67903,
  cardmarket_id: 261352,
  name: "Breaking // Entering",
  lang: "en",
  released_at: "2013-05-03",
  uri: "https://api.scryfall.com/cards/66724f4e-59dd-4c70-b09b-49947320e6d1",
  scryfall_uri: "https://scryfall.com/card/dgm/124/breaking-entering?utm_source=api",
  layout: "split",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/6/6/66724f4e-59dd-4c70-b09b-49947320e6d1.jpg?1562913954",
    normal: "https://cards.scryfall.io/normal/front/6/6/66724f4e-59dd-4c70-b09b-49947320e6d1.jpg?1562913954",
    large: "https://cards.scryfall.io/large/front/6/6/66724f4e-59dd-4c70-b09b-49947320e6d1.jpg?1562913954",
    png: "https://cards.scryfall.io/png/front/6/6/66724f4e-59dd-4c70-b09b-49947320e6d1.png?1562913954",
    art_crop: "https://cards.scryfall.io/art_crop/front/6/6/66724f4e-59dd-4c70-b09b-49947320e6d1.jpg?1562913954",
    border_crop: "https://cards.scryfall.io/border_crop/front/6/6/66724f4e-59dd-4c70-b09b-49947320e6d1.jpg?1562913954",
  },
  mana_cost: "{U}{B} // {4}{B}{R}",
  cmc: 8.0,
  type_line: "Sorcery // Sorcery",
  colors: ["B", "R", "U"],
  color_identity: ["B", "R", "U"],
  keywords: ["Mill", "Fuse"],
  card_faces: [
    {
      object: "card_face",
      name: "Breaking",
      mana_cost: "{U}{B}",
      type_line: "Sorcery",
      oracle_text:
        "Target player mills eight cards.\nFuse (You may cast one or both halves of this card from your hand.)",
      watermark: "dimir",
      artist: "Mathias Kollros",
      artist_id: "2ae0dd12-047c-4efb-80d7-bccc3bac5fba",
      illustration_id: "f32ae122-b28e-4b82-b1d3-0b11e0ed551d",
    },
    {
      object: "card_face",
      name: "Entering",
      flavor_name: "",
      mana_cost: "{4}{B}{R}",
      type_line: "Sorcery",
      oracle_text:
        "Put a creature card from a graveyard onto the battlefield under your control. It gains haste until end of turn.\nFuse (You may cast one or both halves of this card from your hand.)",
      watermark: "rakdos",
      artist: "Mathias Kollros",
      artist_id: "2ae0dd12-047c-4efb-80d7-bccc3bac5fba",
    },
  ],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "not_legal",
    gladiator: "not_legal",
    pioneer: "legal",
    explorer: "not_legal",
    modern: "legal",
    legacy: "legal",
    pauper: "not_legal",
    vintage: "legal",
    penny: "legal",
    commander: "legal",
    oathbreaker: "legal",
    brawl: "not_legal",
    historicbrawl: "not_legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["paper", "mtgo"],
  reserved: false,
  foil: true,
  nonfoil: true,
  finishes: ["nonfoil", "foil"],
  oversized: false,
  promo: false,
  reprint: false,
  variation: false,
  set_id: "c8bd8520-cd98-45cd-b533-8d40c2087426",
  set: "dgm",
  set_name: "Dragon's Maze",
  set_type: "expansion",
  set_uri: "https://api.scryfall.com/sets/c8bd8520-cd98-45cd-b533-8d40c2087426",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Adgm&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/dgm?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/66724f4e-59dd-4c70-b09b-49947320e6d1/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A043370fd-9cfe-47ce-8019-e915cee1ae95&unique=prints",
  collector_number: "124",
  digital: false,
  rarity: "rare",
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "Mathias Kollros",
  artist_ids: ["2ae0dd12-047c-4efb-80d7-bccc3bac5fba"],
  illustration_id: "f32ae122-b28e-4b82-b1d3-0b11e0ed551d",
  border_color: "black",
  frame: "2003",
  full_art: false,
  textless: false,
  booster: true,
  story_spotlight: false,
  edhrec_rank: 15121,
  penny_rank: 6761,
  prices: {
    usd: "0.22",
    usd_foil: "0.44",
    usd_etched: null,
    eur: "0.14",
    eur_foil: "0.15",
    tix: "0.02",
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=369009",
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Breaking+%2F%2F+Entering&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Breaking+%2F%2F+Entering&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Breaking+%2F%2F+Entering",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/product/67903?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Breaking+%2F%2F+Entering&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards/48526?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
