import { ScryfallCard } from "../../../../Card";

// Astral card
const AswanJaguar: ScryfallCard.Normal = {
  object: "card",
  id: "76fab0bc-abc0-4e9f-ae06-b7d748cb073d",
  oracle_id: "9ab97610-76ad-4631-825e-8596dc9cfd4c",
  multiverse_ids: [],
  name: "Aswan Jaguar",
  lang: "en",
  released_at: "1997-04-01",
  uri: "https://api.scryfall.com/cards/76fab0bc-abc0-4e9f-ae06-b7d748cb073d",
  scryfall_uri: "https://scryfall.com/card/past/1/aswan-jaguar?utm_source=api",
  layout: "normal",
  highres_image: false,
  image_status: "lowres",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/7/6/76fab0bc-abc0-4e9f-ae06-b7d748cb073d.jpg?1591116088",
    normal: "https://cards.scryfall.io/normal/front/7/6/76fab0bc-abc0-4e9f-ae06-b7d748cb073d.jpg?1591116088",
    large: "https://cards.scryfall.io/large/front/7/6/76fab0bc-abc0-4e9f-ae06-b7d748cb073d.jpg?1591116088",
    png: "https://cards.scryfall.io/png/front/7/6/76fab0bc-abc0-4e9f-ae06-b7d748cb073d.png?1591116088",
    art_crop: "https://cards.scryfall.io/art_crop/front/7/6/76fab0bc-abc0-4e9f-ae06-b7d748cb073d.jpg?1591116088",
    border_crop: "https://cards.scryfall.io/border_crop/front/7/6/76fab0bc-abc0-4e9f-ae06-b7d748cb073d.jpg?1591116088",
  },
  mana_cost: "{1}{G}{G}",
  cmc: 3.0,
  type_line: "Summon Jaguar",
  oracle_text:
    "When Aswan Jaguar comes into play, choose a random creature type from those in target opponent's deck.\n{G}{G}, {T}: Bury target creature of the chosen type.",
  power: "2",
  toughness: "2",
  colors: ["G"],
  color_identity: ["G"],
  keywords: [],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "not_legal",
    gladiator: "not_legal",
    pioneer: "not_legal",
    explorer: "not_legal",
    modern: "not_legal",
    legacy: "not_legal",
    pauper: "not_legal",
    vintage: "not_legal",
    penny: "not_legal",
    commander: "not_legal",
    oathbreaker: "not_legal",
    brawl: "not_legal",
    historicbrawl: "not_legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "not_legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["astral"],
  reserved: false,
  foil: false,
  nonfoil: true,
  finishes: ["nonfoil"],
  oversized: false,
  promo: false,
  reprint: true,
  variation: false,
  set_id: "9ca75b06-d9c5-4245-9bba-f2751f8d50a5",
  set: "past",
  set_name: "Astral Cards",
  set_type: "box",
  set_uri: "https://api.scryfall.com/sets/9ca75b06-d9c5-4245-9bba-f2751f8d50a5",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Apast&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/past?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/76fab0bc-abc0-4e9f-ae06-b7d748cb073d/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A9ab97610-76ad-4631-825e-8596dc9cfd4c&unique=prints",
  collector_number: "1",
  digital: true,
  rarity: "common",
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "Pat Lewis",
  artist_ids: ["3130411f-ddd5-4cab-a2f4-0a9c3b95a26e"],
  illustration_id: "5fd55524-5cdc-4a17-b907-e8e594567a1c",
  border_color: "black",
  frame: "1997",
  full_art: false,
  textless: false,
  booster: false,
  story_spotlight: false,
  prices: {
    usd: null,
    usd_foil: null,
    usd_etched: null,
    eur: null,
    eur_foil: null,
    tix: null,
  },
  related_uris: {
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Aswan+Jaguar&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Aswan+Jaguar&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Aswan+Jaguar",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/search/magic/product?productLineName=magic&q=Aswan+Jaguar&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall&view=grid",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Aswan+Jaguar&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Aswan+Jaguar&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
