import { ScryfallCard } from "src";

const AbbotOfKeralKeep: ScryfallCard.Normal = {
  object: "card",
  id: "355dcac7-120b-4c52-b077-bf36c41c579d",
  oracle_id: "09be0f69-9c7f-491f-964d-bfbbc2d4251f",
  multiverse_ids: [573414],
  tcgplayer_etched_id: 277244,
  cardmarket_id: 665838,
  name: "Abbot of Keral Keep",
  lang: "en",
  released_at: "2022-07-08",
  uri: "https://api.scryfall.com/cards/355dcac7-120b-4c52-b077-bf36c41c579d",
  scryfall_uri: "https://scryfall.com/card/2x2/446/abbot-of-keral-keep?utm_source=api",
  layout: "normal",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/3/5/355dcac7-120b-4c52-b077-bf36c41c579d.jpg?1681411237",
    normal: "https://cards.scryfall.io/normal/front/3/5/355dcac7-120b-4c52-b077-bf36c41c579d.jpg?1681411237",
    large: "https://cards.scryfall.io/large/front/3/5/355dcac7-120b-4c52-b077-bf36c41c579d.jpg?1681411237",
    png: "https://cards.scryfall.io/png/front/3/5/355dcac7-120b-4c52-b077-bf36c41c579d.png?1681411237",
    art_crop: "https://cards.scryfall.io/art_crop/front/3/5/355dcac7-120b-4c52-b077-bf36c41c579d.jpg?1681411237",
    border_crop: "https://cards.scryfall.io/border_crop/front/3/5/355dcac7-120b-4c52-b077-bf36c41c579d.jpg?1681411237",
  },
  mana_cost: "{1}{R}",
  cmc: 2.0,
  type_line: "Creature — Human Monk",
  oracle_text:
    "Prowess (Whenever you cast a noncreature spell, this creature gets +1/+1 until end of turn.)\nWhen Abbot of Keral Keep enters the battlefield, exile the top card of your library. Until end of turn, you may play that card.",
  power: "2",
  toughness: "1",
  colors: ["R"],
  color_identity: ["R"],
  keywords: ["Prowess"],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "legal",
    gladiator: "legal",
    pioneer: "legal",
    explorer: "legal",
    modern: "legal",
    legacy: "legal",
    pauper: "not_legal",
    vintage: "legal",
    penny: "legal",
    commander: "legal",
    oathbreaker: "legal",
    brawl: "not_legal",
    historicbrawl: "legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["paper"],
  reserved: false,
  foil: false,
  nonfoil: false,
  finishes: ["etched"],
  oversized: false,
  promo: false,
  reprint: true,
  variation: false,
  set_id: "5a645837-b050-449f-ac90-1e7ccbf45031",
  set: "2x2",
  set_name: "Double Masters 2022",
  set_type: "masters",
  set_uri: "https://api.scryfall.com/sets/5a645837-b050-449f-ac90-1e7ccbf45031",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3A2x2&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/2x2?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/355dcac7-120b-4c52-b077-bf36c41c579d/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A09be0f69-9c7f-491f-964d-bfbbc2d4251f&unique=prints",
  collector_number: "446",
  digital: false,
  rarity: "rare",
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "Deruchenko Alexander",
  artist_ids: ["806f6ff9-6ed4-4e93-998a-a562c0b792e6"],
  illustration_id: "f13bdef1-c3f5-4bcb-bc6f-c37b46eda154",
  border_color: "black",
  frame: "2015",
  frame_effects: ["inverted"],
  security_stamp: "oval",
  full_art: false,
  textless: false,
  booster: false,
  story_spotlight: false,
  promo_types: ["boosterfun"],
  edhrec_rank: 10319,
  penny_rank: 636,
  preview: {
    source: "Wizards of the Coast",
    source_uri: "https://www.twitch.tv/videos/1512208234",
    previewed_at: "2022-06-23",
  },
  prices: {
    usd: null,
    usd_foil: null,
    usd_etched: "1.12",
    eur: null,
    eur_foil: null,
    tix: null,
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=573414",
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Abbot+of+Keral+Keep&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Abbot+of+Keral+Keep&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Abbot+of+Keral+Keep",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/search/magic/product?productLineName=magic&q=Abbot+of+Keral+Keep&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall&view=grid",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Abbot+of+Keral+Keep&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Abbot+of+Keral+Keep&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
