import { ScryfallCard } from "src";

const Bontu: ScryfallCard.Normal = {
  object: "card",
  id: "2ae1bb79-a931-4d2e-9cc9-a06862dc5cde",
  oracle_id: "183891b0-b5ec-47f4-8d09-b9d3cfc4e7f1",
  multiverse_ids: [],
  tcgplayer_id: 193822,
  cardmarket_id: 380331,
  name: "God-Eternal Bontu",
  lang: "en",
  released_at: "2019-07-18",
  uri: "https://api.scryfall.com/cards/2ae1bb79-a931-4d2e-9cc9-a06862dc5cde",
  scryfall_uri: "https://scryfall.com/card/ps19/92/god-eternal-bontu?utm_source=api",
  layout: "normal",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/2/a/2ae1bb79-a931-4d2e-9cc9-a06862dc5cde.jpg?1671425783",
    normal: "https://cards.scryfall.io/normal/front/2/a/2ae1bb79-a931-4d2e-9cc9-a06862dc5cde.jpg?1671425783",
    large: "https://cards.scryfall.io/large/front/2/a/2ae1bb79-a931-4d2e-9cc9-a06862dc5cde.jpg?1671425783",
    png: "https://cards.scryfall.io/png/front/2/a/2ae1bb79-a931-4d2e-9cc9-a06862dc5cde.png?1671425783",
    art_crop: "https://cards.scryfall.io/art_crop/front/2/a/2ae1bb79-a931-4d2e-9cc9-a06862dc5cde.jpg?1671425783",
    border_crop: "https://cards.scryfall.io/border_crop/front/2/a/2ae1bb79-a931-4d2e-9cc9-a06862dc5cde.jpg?1671425783",
  },
  mana_cost: "{3}{B}{B}",
  cmc: 5.0,
  type_line: "Legendary Creature — Zombie God",
  oracle_text:
    "Menace\nWhen God-Eternal Bontu enters the battlefield, sacrifice any number of other permanents, then draw that many cards.\nWhen God-Eternal Bontu dies or is put into exile from the battlefield, you may put it into its owner's library third from the top.",
  power: "5",
  toughness: "6",
  colors: ["B"],
  color_identity: ["B"],
  keywords: ["Menace"],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "legal",
    gladiator: "legal",
    pioneer: "legal",
    explorer: "legal",
    modern: "legal",
    legacy: "legal",
    pauper: "not_legal",
    vintage: "legal",
    penny: "not_legal",
    commander: "legal",
    oathbreaker: "legal",
    brawl: "not_legal",
    historicbrawl: "legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["paper"],
  reserved: false,
  foil: false,
  nonfoil: true,
  finishes: ["nonfoil"],
  oversized: false,
  promo: true,
  reprint: true,
  variation: false,
  set_id: "9e585a9c-2bba-4310-94a9-036329ee264c",
  set: "ps19",
  set_name: "San Diego Comic-Con 2019",
  set_type: "promo",
  set_uri: "https://api.scryfall.com/sets/9e585a9c-2bba-4310-94a9-036329ee264c",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aps19&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/ps19?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/2ae1bb79-a931-4d2e-9cc9-a06862dc5cde/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A183891b0-b5ec-47f4-8d09-b9d3cfc4e7f1&unique=prints",
  collector_number: "92",
  digital: false,
  rarity: "mythic",
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "Adam Paquette",
  artist_ids: ["89023dad-e6c0-41e0-83fb-eb2bfbbdc3f2"],
  illustration_id: "95da2b4d-8682-48d3-912a-b86f67f034c9",
  border_color: "black",
  frame: "2015",
  frame_effects: ["legendary"],
  security_stamp: "oval",
  full_art: false,
  textless: false,
  booster: false,
  story_spotlight: false,
  promo_types: ["convention", "glossy"],
  edhrec_rank: 2844,
  preview: {
    source: "Gizmodo",
    source_uri: "https://io9.gizmodo.com/magic-the-gatherings-comic-con-exclusive-brings-forth-1835871979",
    previewed_at: "2019-06-26",
  },
  prices: {
    usd: "24.84",
    usd_foil: null,
    usd_etched: null,
    eur: "25.99",
    eur_foil: null,
    tix: null,
  },
  related_uris: {
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=God-Eternal+Bontu&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=God-Eternal+Bontu&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=God-Eternal+Bontu",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/product/193822?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=God-Eternal+Bontu&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=God-Eternal+Bontu&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
