import { ScryfallCard } from "src";

const Akroma: TestCard<ScryfallCard.Vanguard> = {
  object: "card",
  id: "61b07ae0-44f5-4ffe-a33b-96885d4fc26b",
  oracle_id: "eaa10dee-89da-43eb-b339-1cf59e488344",
  multiverse_ids: [182290],
  mtgo_id: 19,
  name: "Akroma, Angel of Wrath Avatar",
  lang: "en",
  released_at: "2003-01-01",
  uri: "https://api.scryfall.com/cards/61b07ae0-44f5-4ffe-a33b-96885d4fc26b",
  scryfall_uri: "https://scryfall.com/card/pmoa/33/akroma-angel-of-wrath-avatar?utm_source=api",
  layout: "vanguard",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/6/1/61b07ae0-44f5-4ffe-a33b-96885d4fc26b.jpg?1562917989",
    normal: "https://cards.scryfall.io/normal/front/6/1/61b07ae0-44f5-4ffe-a33b-96885d4fc26b.jpg?1562917989",
    large: "https://cards.scryfall.io/large/front/6/1/61b07ae0-44f5-4ffe-a33b-96885d4fc26b.jpg?1562917989",
    png: "https://cards.scryfall.io/png/front/6/1/61b07ae0-44f5-4ffe-a33b-96885d4fc26b.png?1562917989",
    art_crop: "https://cards.scryfall.io/art_crop/front/6/1/61b07ae0-44f5-4ffe-a33b-96885d4fc26b.jpg?1562917989",
    border_crop: "https://cards.scryfall.io/border_crop/front/6/1/61b07ae0-44f5-4ffe-a33b-96885d4fc26b.jpg?1562917989",
  },
  mana_cost: "",
  cmc: 0,
  type_line: "Vanguard",
  oracle_text:
    "Whenever a creature enters the battlefield under your control, it gains two abilities chosen at random from flying, first strike, trample, haste, protection from black, protection from red, and vigilance.",
  life_modifier: "+7",
  hand_modifier: "+1",
  colors: [],
  color_identity: [],
  keywords: ["First strike", "Protection", "Haste", "Trample"],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "not_legal",
    gladiator: "not_legal",
    pioneer: "not_legal",
    explorer: "not_legal",
    modern: "not_legal",
    legacy: "not_legal",
    pauper: "not_legal",
    vintage: "not_legal",
    penny: "not_legal",
    commander: "not_legal",
    oathbreaker: "not_legal",
    brawl: "not_legal",
    historicbrawl: "not_legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "not_legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["mtgo"],
  reserved: false,
  foil: true,
  nonfoil: true,
  finishes: ["nonfoil", "foil"],
  oversized: false,
  promo: false,
  reprint: false,
  variation: false,
  set_id: "f8778e61-ae6b-43ee-a611-f042439fa737",
  set: "pmoa",
  set_name: "Magic Online Avatars",
  set_type: "vanguard",
  set_uri: "https://api.scryfall.com/sets/f8778e61-ae6b-43ee-a611-f042439fa737",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Apmoa&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/pmoa?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/61b07ae0-44f5-4ffe-a33b-96885d4fc26b/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Aeaa10dee-89da-43eb-b339-1cf59e488344&unique=prints",
  collector_number: "33",
  digital: true,
  rarity: "rare",
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "UDON",
  artist_ids: ["1aa5b0cc-259b-40f0-b236-6866876b917a"],
  illustration_id: "b919c0c7-a294-4044-8af0-ce5175b5cf27",
  border_color: "black",
  frame: "2015",
  full_art: false,
  textless: false,
  booster: false,
  story_spotlight: false,
  prices: {
    usd: null,
    usd_foil: null,
    usd_etched: null,
    eur: null,
    eur_foil: null,
    tix: "0.02",
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=182290",
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Akroma%2C+Angel+of+Wrath+Avatar&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Akroma%2C+Angel+of+Wrath+Avatar&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Akroma%2C+Angel+of+Wrath+Avatar",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/search/magic/product?productLineName=magic&q=Akroma%2C+Angel+of+Wrath+Avatar&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall&view=grid",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Akroma%2C+Angel+of+Wrath+Avatar&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards/19?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
