import { ScryfallCard } from "src";

const Punchcard: TestCard<ScryfallCard.Token> = {
  object: "card",
  id: "abe8eefe-c9f8-43f7-a348-8afee8b0ec68",
  oracle_id: "dff5472c-9018-4501-920d-03ffc6dbb242",
  multiverse_ids: [],
  name: "Ability Punchcard",
  lang: "en",
  released_at: "2020-04-24",
  uri: "https://api.scryfall.com/cards/abe8eefe-c9f8-43f7-a348-8afee8b0ec68",
  scryfall_uri: "https://scryfall.com/card/tiko/14/ability-punchcard?utm_source=api",
  layout: "token",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/a/b/abe8eefe-c9f8-43f7-a348-8afee8b0ec68.jpg?1595719605",
    normal: "https://cards.scryfall.io/normal/front/a/b/abe8eefe-c9f8-43f7-a348-8afee8b0ec68.jpg?1595719605",
    large: "https://cards.scryfall.io/large/front/a/b/abe8eefe-c9f8-43f7-a348-8afee8b0ec68.jpg?1595719605",
    png: "https://cards.scryfall.io/png/front/a/b/abe8eefe-c9f8-43f7-a348-8afee8b0ec68.png?1595719605",
    art_crop: "https://cards.scryfall.io/art_crop/front/a/b/abe8eefe-c9f8-43f7-a348-8afee8b0ec68.jpg?1595719605",
    border_crop: "https://cards.scryfall.io/border_crop/front/a/b/abe8eefe-c9f8-43f7-a348-8afee8b0ec68.jpg?1595719605",
  },
  mana_cost: "",
  cmc: 0.0,
  type_line: "Card",
  oracle_text: "",
  colors: [],
  color_identity: [],
  keywords: [],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "not_legal",
    gladiator: "not_legal",
    pioneer: "not_legal",
    explorer: "not_legal",
    modern: "not_legal",
    legacy: "not_legal",
    pauper: "not_legal",
    vintage: "not_legal",
    penny: "not_legal",
    commander: "not_legal",
    oathbreaker: "not_legal",
    brawl: "not_legal",
    historicbrawl: "not_legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "not_legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["paper"],
  reserved: false,
  foil: false,
  nonfoil: true,
  finishes: ["nonfoil"],
  oversized: false,
  promo: false,
  reprint: true,
  variation: false,
  set_id: "382e0900-dd85-4f23-9dcf-24c9d2971f1b",
  set: "tiko",
  set_name: "Ikoria: Lair of Behemoths Tokens",
  set_type: "token",
  set_uri: "https://api.scryfall.com/sets/382e0900-dd85-4f23-9dcf-24c9d2971f1b",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Atiko&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/tiko?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/abe8eefe-c9f8-43f7-a348-8afee8b0ec68/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Adff5472c-9018-4501-920d-03ffc6dbb242&unique=prints",
  collector_number: "14",
  digital: false,
  rarity: "common",
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "",
  border_color: "black",
  frame: "2015",
  full_art: false,
  textless: false,
  booster: false,
  story_spotlight: false,
  prices: {
    usd: null,
    usd_foil: null,
    usd_etched: null,
    eur: null,
    eur_foil: null,
    tix: null,
  },
  related_uris: {
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Ability+Punchcard&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Ability+Punchcard&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Ability+Punchcard",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/search/magic/product?productLineName=magic&q=Ability+Punchcard&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall&view=grid",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Ability+Punchcard&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Ability+Punchcard&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
