import { ScryfallCard } from "src";

const Vizier: ScryfallCard.Token = {
  object: "card",
  id: "39520c16-1f4b-4f15-aeb4-53c91e8ecfcc",
  oracle_id: "c97e158a-a1be-446c-b9aa-cae931735b9d",
  multiverse_ids: [],
  tcgplayer_id: 130157,
  name: "Vizier of Many Faces",
  lang: "en",
  released_at: "2017-04-28",
  uri: "https://api.scryfall.com/cards/39520c16-1f4b-4f15-aeb4-53c91e8ecfcc",
  scryfall_uri: "https://scryfall.com/card/takh/15/vizier-of-many-faces?utm_source=api",
  layout: "token",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/3/9/39520c16-1f4b-4f15-aeb4-53c91e8ecfcc.jpg?1562844791",
    normal: "https://cards.scryfall.io/normal/front/3/9/39520c16-1f4b-4f15-aeb4-53c91e8ecfcc.jpg?1562844791",
    large: "https://cards.scryfall.io/large/front/3/9/39520c16-1f4b-4f15-aeb4-53c91e8ecfcc.jpg?1562844791",
    png: "https://cards.scryfall.io/png/front/3/9/39520c16-1f4b-4f15-aeb4-53c91e8ecfcc.png?1562844791",
    art_crop: "https://cards.scryfall.io/art_crop/front/3/9/39520c16-1f4b-4f15-aeb4-53c91e8ecfcc.jpg?1562844791",
    border_crop: "https://cards.scryfall.io/border_crop/front/3/9/39520c16-1f4b-4f15-aeb4-53c91e8ecfcc.jpg?1562844791",
  },
  mana_cost: "",
  cmc: 0.0,
  type_line: "Token Creature — Zombie Shapeshifter Cleric",
  oracle_text:
    "You may have Vizier of Many Faces enter the battlefield as a copy of any creature on the battlefield, except has no mana cost, it's white, and it's a Zombie in addition to its other types.",
  power: "0",
  toughness: "0",
  colors: ["W"],
  color_identity: ["W"],
  keywords: [],
  all_parts: [
    {
      object: "related_card",
      id: "386577fe-9322-4168-bdcd-ecebb2f51e01",
      component: "combo_piece",
      name: "Vizier of Many Faces",
      type_line: "Creature — Shapeshifter Cleric",
      uri: "https://api.scryfall.com/cards/386577fe-9322-4168-bdcd-ecebb2f51e01",
    },
    {
      object: "related_card",
      id: "39520c16-1f4b-4f15-aeb4-53c91e8ecfcc",
      component: "token",
      name: "Vizier of Many Faces",
      type_line: "Token Creature — Zombie Shapeshifter Cleric",
      uri: "https://api.scryfall.com/cards/39520c16-1f4b-4f15-aeb4-53c91e8ecfcc",
    },
  ],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "not_legal",
    gladiator: "not_legal",
    pioneer: "not_legal",
    explorer: "not_legal",
    modern: "not_legal",
    legacy: "not_legal",
    pauper: "not_legal",
    vintage: "not_legal",
    penny: "not_legal",
    commander: "not_legal",
    oathbreaker: "not_legal",
    brawl: "not_legal",
    historicbrawl: "not_legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "not_legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["paper"],
  reserved: false,
  foil: false,
  nonfoil: true,
  finishes: ["nonfoil"],
  oversized: false,
  promo: false,
  reprint: false,
  variation: false,
  set_id: "739edf06-0069-4a07-8995-18ff67083e8e",
  set: "takh",
  set_name: "Amonkhet Tokens",
  set_type: "token",
  set_uri: "https://api.scryfall.com/sets/739edf06-0069-4a07-8995-18ff67083e8e",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Atakh&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/takh?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/39520c16-1f4b-4f15-aeb4-53c91e8ecfcc/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Ac97e158a-a1be-446c-b9aa-cae931735b9d&unique=prints",
  collector_number: "15",
  digital: false,
  rarity: "common",
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "Ryan Yee",
  artist_ids: ["8955dca7-3e37-42b4-83a9-167c78a2178f"],
  illustration_id: "7485b910-64c1-4d42-aa10-0f9d97c98c62",
  border_color: "black",
  frame: "2015",
  full_art: false,
  textless: false,
  booster: true,
  story_spotlight: false,
  promo_types: ["setpromo"],
  prices: {
    usd: "1.20",
    usd_foil: null,
    usd_etched: null,
    eur: null,
    eur_foil: null,
    tix: null,
  },
  related_uris: {
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Vizier+of+Many+Faces&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Vizier+of+Many+Faces&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Vizier+of+Many+Faces",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/product/130157?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Vizier+of+Many+Faces&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Vizier+of+Many+Faces&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
