import { ScryfallCard } from "src";

const Brisela: TestCard<ScryfallCard.Meld> = {
  object: "card",
  id: "5a7a212e-e0b6-4f12-a95c-173cae023f93",
  oracle_id: "b23587e0-9fb7-492e-8bb4-f218e8e4ce6c",
  multiverse_ids: [414305],
  name: "Brisela, Voice of Nightmares",
  lang: "en",
  released_at: "2016-07-22",
  uri: "https://api.scryfall.com/cards/5a7a212e-e0b6-4f12-a95c-173cae023f93",
  scryfall_uri: "https://scryfall.com/card/emn/15b/brisela-voice-of-nightmares?utm_source=api",
  layout: "meld",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/5/a/5a7a212e-e0b6-4f12-a95c-173cae023f93.jpg?1679517857",
    normal: "https://cards.scryfall.io/normal/front/5/a/5a7a212e-e0b6-4f12-a95c-173cae023f93.jpg?1679517857",
    large: "https://cards.scryfall.io/large/front/5/a/5a7a212e-e0b6-4f12-a95c-173cae023f93.jpg?1679517857",
    png: "https://cards.scryfall.io/png/front/5/a/5a7a212e-e0b6-4f12-a95c-173cae023f93.png?1679517857",
    art_crop: "https://cards.scryfall.io/art_crop/front/5/a/5a7a212e-e0b6-4f12-a95c-173cae023f93.jpg?1679517857",
    border_crop: "https://cards.scryfall.io/border_crop/front/5/a/5a7a212e-e0b6-4f12-a95c-173cae023f93.jpg?1679517857",
  },
  mana_cost: "",
  cmc: 11.0,
  type_line: "Legendary Creature — Eldrazi Angel",
  oracle_text: "Flying, first strike, vigilance, lifelink\nYour opponents can't cast spells with mana value 3 or less.",
  power: "9",
  toughness: "10",
  colors: [],
  color_identity: ["W"],
  keywords: ["Flying", "Lifelink", "Vigilance", "First strike"],
  all_parts: [
    {
      object: "related_card",
      id: "5a7a212e-e0b6-4f12-a95c-173cae023f93",
      component: "meld_result",
      name: "Brisela, Voice of Nightmares",
      type_line: "Legendary Creature — Eldrazi Angel",
      uri: "https://api.scryfall.com/cards/5a7a212e-e0b6-4f12-a95c-173cae023f93",
    },
    {
      object: "related_card",
      id: "27907985-b5f6-4098-ab43-15a0c2bf94d5",
      component: "meld_part",
      name: "Bruna, the Fading Light",
      type_line: "Legendary Creature — Angel Horror",
      uri: "https://api.scryfall.com/cards/27907985-b5f6-4098-ab43-15a0c2bf94d5",
    },
    {
      object: "related_card",
      id: "c75c035a-7da9-4b36-982d-fca8220b1797",
      component: "meld_part",
      name: "Gisela, the Broken Blade",
      type_line: "Legendary Creature — Angel Horror",
      uri: "https://api.scryfall.com/cards/c75c035a-7da9-4b36-982d-fca8220b1797",
    },
  ],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "legal",
    gladiator: "legal",
    pioneer: "legal",
    explorer: "legal",
    modern: "legal",
    legacy: "legal",
    pauper: "not_legal",
    vintage: "legal",
    penny: "not_legal",
    commander: "legal",
    oathbreaker: "legal",
    brawl: "not_legal",
    historicbrawl: "legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["paper", "mtgo"],
  reserved: false,
  foil: true,
  nonfoil: true,
  finishes: ["nonfoil", "foil"],
  oversized: false,
  promo: false,
  reprint: false,
  variation: false,
  set_id: "5f0e4093-334f-4439-bbb5-a0affafd0ffc",
  set: "emn",
  set_name: "Eldritch Moon",
  set_type: "expansion",
  set_uri: "https://api.scryfall.com/sets/5f0e4093-334f-4439-bbb5-a0affafd0ffc",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aemn&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/emn?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/5a7a212e-e0b6-4f12-a95c-173cae023f93/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Ab23587e0-9fb7-492e-8bb4-f218e8e4ce6c&unique=prints",
  collector_number: "15b",
  digital: false,
  rarity: "mythic",
  flavor_text: "Upon discovering what had become of her sisters, Sigarda could only weep.",
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "Clint Cearley",
  artist_ids: ["03b75350-d5a0-4e3a-b3b4-8d4a5554385b"],
  illustration_id: "9528e065-5297-4d91-bf75-3c175b54f0d4",
  border_color: "black",
  frame: "2015",
  frame_effects: ["mooneldrazidfc"],
  full_art: false,
  textless: false,
  booster: true,
  story_spotlight: false,
  prices: {
    usd: null,
    usd_foil: null,
    usd_etched: null,
    eur: null,
    eur_foil: null,
    tix: null,
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=414305",
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Brisela%2C+Voice+of+Nightmares&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Brisela%2C+Voice+of+Nightmares&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Brisela%2C+Voice+of+Nightmares",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/search/magic/product?productLineName=magic&q=Brisela%2C+Voice+of+Nightmares&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall&view=grid",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Brisela%2C+Voice+of+Nightmares&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Brisela%2C+Voice+of+Nightmares&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
