import { ScryfallCard } from "src";

const Okaun: ScryfallCard.ReversibleCard = {
  object: "card",
  id: "94eea6e3-20bc-4dab-90ba-3113c120fb90",
  multiverse_ids: [],
  tcgplayer_id: 259213,
  name: "Okaun, Eye of Chaos // Okaun, Eye of Chaos",
  lang: "en",
  released_at: "2022-04-22",
  uri: "https://api.scryfall.com/cards/94eea6e3-20bc-4dab-90ba-3113c120fb90",
  scryfall_uri: "https://scryfall.com/card/sld/380/okaun-eye-of-chaos-okaun-eye-of-chaos?utm_source=api",
  layout: "reversible_card",
  highres_image: true,
  image_status: "highres_scan",
  color_identity: ["R"],
  keywords: ["Partner with", "Partner"],
  card_faces: [
    {
      object: "card_face",
      oracle_id: "7dec219b-96d1-4d4c-b3ac-15eda9d2ccc6",
      layout: "normal",
      name: "Okaun, Eye of Chaos",
      mana_cost: "{4}{R}",
      cmc: 5.0,
      type_line: "Legendary Creature — Cyclops Berserker",
      oracle_text:
        "Partner with Zndrsplt, Eye of Wisdom (When this creature enters the battlefield, target player may put Zndrsplt into their hand from their library, then shuffle.)\nAt the beginning of combat on your turn, flip a coin until you lose a flip.\nWhenever a player wins a coin flip, double Okaun's power and toughness until end of turn.",
      colors: ["R"],
      power: "3",
      toughness: "3",
      artist: "Alexis Ziritt",
      artist_id: "add4cc84-9254-4c0b-8fcd-af4a238bdbd5",
      illustration_id: "65a493a1-ed73-4d07-a7aa-7c9c6ed76de9",
      image_uris: {
        small: "https://cards.scryfall.io/small/front/9/4/94eea6e3-20bc-4dab-90ba-3113c120fb90.jpg?1670031714",
        normal: "https://cards.scryfall.io/normal/front/9/4/94eea6e3-20bc-4dab-90ba-3113c120fb90.jpg?1670031714",
        large: "https://cards.scryfall.io/large/front/9/4/94eea6e3-20bc-4dab-90ba-3113c120fb90.jpg?1670031714",
        png: "https://cards.scryfall.io/png/front/9/4/94eea6e3-20bc-4dab-90ba-3113c120fb90.png?1670031714",
        art_crop: "https://cards.scryfall.io/art_crop/front/9/4/94eea6e3-20bc-4dab-90ba-3113c120fb90.jpg?1670031714",
        border_crop:
          "https://cards.scryfall.io/border_crop/front/9/4/94eea6e3-20bc-4dab-90ba-3113c120fb90.jpg?1670031714",
      },
    },
    {
      object: "card_face",
      oracle_id: "7dec219b-96d1-4d4c-b3ac-15eda9d2ccc6",
      layout: "normal",
      name: "Okaun, Eye of Chaos",
      flavor_name: "",
      mana_cost: "{4}{R}",
      cmc: 5.0,
      type_line: "Legendary Creature — Cyclops Berserker",
      oracle_text:
        "Partner with Zndrsplt, Eye of Wisdom (When this creature enters the battlefield, target player may put Zndrsplt into their hand from their library, then shuffle.)\nAt the beginning of combat on your turn, flip a coin until you lose a flip.\nWhenever a player wins a coin flip, double Okaun's power and toughness until end of turn.",
      colors: ["R"],
      power: "3",
      toughness: "3",
      artist: "Alexis Ziritt",
      artist_id: "add4cc84-9254-4c0b-8fcd-af4a238bdbd5",
      illustration_id: "e8954b3c-0a80-484f-9e8d-ef77117f9d68",
      image_uris: {
        small: "https://cards.scryfall.io/small/back/9/4/94eea6e3-20bc-4dab-90ba-3113c120fb90.jpg?1670031714",
        normal: "https://cards.scryfall.io/normal/back/9/4/94eea6e3-20bc-4dab-90ba-3113c120fb90.jpg?1670031714",
        large: "https://cards.scryfall.io/large/back/9/4/94eea6e3-20bc-4dab-90ba-3113c120fb90.jpg?1670031714",
        png: "https://cards.scryfall.io/png/back/9/4/94eea6e3-20bc-4dab-90ba-3113c120fb90.png?1670031714",
        art_crop: "https://cards.scryfall.io/art_crop/back/9/4/94eea6e3-20bc-4dab-90ba-3113c120fb90.jpg?1670031714",
        border_crop:
          "https://cards.scryfall.io/border_crop/back/9/4/94eea6e3-20bc-4dab-90ba-3113c120fb90.jpg?1670031714",
      },
    },
  ],
  all_parts: [
    {
      object: "related_card",
      id: "e25ce640-baf5-442b-8b75-d05dd9fb20dd",
      component: "combo_piece",
      name: "Zndrsplt, Eye of Wisdom // Zndrsplt, Eye of Wisdom",
      type_line: "Legendary Creature — Homunculus // Legendary Creature — Homunculus",
      uri: "https://api.scryfall.com/cards/e25ce640-baf5-442b-8b75-d05dd9fb20dd",
    },
    {
      object: "related_card",
      id: "8421ad46-dc7f-4b66-800b-e41c30835300",
      component: "combo_piece",
      name: "Okaun, Eye of Chaos // Okaun, Eye of Chaos",
      type_line: "Legendary Creature — Cyclops Berserker // Legendary Creature — Cyclops Berserker",
      uri: "https://api.scryfall.com/cards/8421ad46-dc7f-4b66-800b-e41c30835300",
    },
  ],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "not_legal",
    gladiator: "not_legal",
    pioneer: "not_legal",
    explorer: "not_legal",
    modern: "not_legal",
    legacy: "legal",
    pauper: "not_legal",
    vintage: "legal",
    penny: "not_legal",
    commander: "legal",
    oathbreaker: "legal",
    brawl: "not_legal",
    historicbrawl: "not_legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["paper"],
  reserved: false,
  foil: true,
  nonfoil: false,
  finishes: ["foil"],
  oversized: false,
  promo: false,
  reprint: true,
  variation: false,
  set_id: "4d92a8a7-ccb0-437d-abdc-9d70fc5ed672",
  set: "sld",
  set_name: "Secret Lair Drop",
  set_type: "box",
  set_uri: "https://api.scryfall.com/sets/4d92a8a7-ccb0-437d-abdc-9d70fc5ed672",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Asld&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/sld?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/94eea6e3-20bc-4dab-90ba-3113c120fb90/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A7dec219b-96d1-4d4c-b3ac-15eda9d2ccc6&unique=prints",
  collector_number: "380",
  digital: false,
  rarity: "rare",
  artist: "Alexis Ziritt",
  artist_ids: ["add4cc84-9254-4c0b-8fcd-af4a238bdbd5"],
  border_color: "borderless",
  frame: "2015",
  frame_effects: ["legendary", "inverted"],
  security_stamp: "oval",
  full_art: false,
  textless: false,
  booster: false,
  story_spotlight: false,
  edhrec_rank: 5803,
  prices: {
    usd: null,
    usd_foil: "7.20",
    usd_etched: null,
    eur: null,
    eur_foil: null,
    tix: null,
  },
  related_uris: {
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Okaun%2C+Eye+of+Chaos+%2F%2F+Okaun%2C+Eye+of+Chaos&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Okaun%2C+Eye+of+Chaos+%2F%2F+Okaun%2C+Eye+of+Chaos&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Okaun%2C+Eye+of+Chaos+%2F%2F+Okaun%2C+Eye+of+Chaos",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/product/259213?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Okaun%2C+Eye+of+Chaos+%2F%2F+Okaun%2C+Eye+of+Chaos&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Okaun%2C+Eye+of+Chaos+%2F%2F+Okaun%2C+Eye+of+Chaos&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
