import { ScryfallCard } from "src";

const Shaile: TestCard<ScryfallCard.ModalDfc> = {
  object: "card",
  id: "938cee8f-ac2c-49a5-9ff7-1367d0edfabe",
  oracle_id: "b0907441-30fe-436a-b29c-585b57eabfc3",
  multiverse_ids: [513646, 513647],
  mtgo_id: 88815,
  arena_id: 76562,
  tcgplayer_id: 235204,
  cardmarket_id: 556448,
  name: "Shaile, Dean of Radiance // Embrose, Dean of Shadow",
  lang: "en",
  released_at: "2021-04-23",
  uri: "https://api.scryfall.com/cards/938cee8f-ac2c-49a5-9ff7-1367d0edfabe",
  scryfall_uri: "https://scryfall.com/card/stx/158/shaile-dean-of-radiance-embrose-dean-of-shadow?utm_source=api",
  layout: "modal_dfc",
  highres_image: true,
  image_status: "highres_scan",
  cmc: 2.0,
  type_line: "Legendary Creature — Bird Cleric // Legendary Creature — Human Warlock",
  color_identity: ["B", "W"],
  keywords: ["Flying", "Vigilance"],
  card_faces: [
    {
      object: "card_face",
      name: "Shaile, Dean of Radiance",
      mana_cost: "{1}{W}",
      type_line: "Legendary Creature — Bird Cleric",
      oracle_text:
        "Flying, vigilance\n{T}: Put a +1/+1 counter on each creature that entered the battlefield under your control this turn.",
      colors: ["W"],
      power: "1",
      toughness: "1",
      flavor_text: '"You are so much stronger than you know."',
      watermark: "silverquill",
      artist: "Yongjae Choi",
      artist_id: "5ab91c3b-a6da-4751-a56e-81d0f61a67ab",
      illustration_id: "6f1dedd5-99ab-43ab-8a9c-9d095a5d18c4",
      image_uris: {
        small: "https://cards.scryfall.io/small/front/9/3/938cee8f-ac2c-49a5-9ff7-1367d0edfabe.jpg?1634060541",
        normal: "https://cards.scryfall.io/normal/front/9/3/938cee8f-ac2c-49a5-9ff7-1367d0edfabe.jpg?1634060541",
        large: "https://cards.scryfall.io/large/front/9/3/938cee8f-ac2c-49a5-9ff7-1367d0edfabe.jpg?1634060541",
        png: "https://cards.scryfall.io/png/front/9/3/938cee8f-ac2c-49a5-9ff7-1367d0edfabe.png?1634060541",
        art_crop: "https://cards.scryfall.io/art_crop/front/9/3/938cee8f-ac2c-49a5-9ff7-1367d0edfabe.jpg?1634060541",
        border_crop:
          "https://cards.scryfall.io/border_crop/front/9/3/938cee8f-ac2c-49a5-9ff7-1367d0edfabe.jpg?1634060541",
      },
    },
    {
      object: "card_face",
      name: "Embrose, Dean of Shadow",
      flavor_name: "",
      mana_cost: "{2}{B}{B}",
      type_line: "Legendary Creature — Human Warlock",
      oracle_text:
        "{T}: Put a +1/+1 counter on another target creature, then Embrose, Dean of Shadow deals 2 damage to that creature.\nWhenever a creature you control with a +1/+1 counter on it dies, draw a card.",
      colors: ["B"],
      power: "4",
      toughness: "4",
      watermark: "silverquill",
      artist: "Yongjae Choi",
      artist_id: "5ab91c3b-a6da-4751-a56e-81d0f61a67ab",
      illustration_id: "fff88913-8706-4e92-be06-65d069990655",
      image_uris: {
        small: "https://cards.scryfall.io/small/back/9/3/938cee8f-ac2c-49a5-9ff7-1367d0edfabe.jpg?1634060541",
        normal: "https://cards.scryfall.io/normal/back/9/3/938cee8f-ac2c-49a5-9ff7-1367d0edfabe.jpg?1634060541",
        large: "https://cards.scryfall.io/large/back/9/3/938cee8f-ac2c-49a5-9ff7-1367d0edfabe.jpg?1634060541",
        png: "https://cards.scryfall.io/png/back/9/3/938cee8f-ac2c-49a5-9ff7-1367d0edfabe.png?1634060541",
        art_crop: "https://cards.scryfall.io/art_crop/back/9/3/938cee8f-ac2c-49a5-9ff7-1367d0edfabe.jpg?1634060541",
        border_crop:
          "https://cards.scryfall.io/border_crop/back/9/3/938cee8f-ac2c-49a5-9ff7-1367d0edfabe.jpg?1634060541",
      },
    },
  ],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "legal",
    gladiator: "legal",
    pioneer: "legal",
    explorer: "legal",
    modern: "legal",
    legacy: "legal",
    pauper: "not_legal",
    vintage: "legal",
    penny: "legal",
    commander: "legal",
    oathbreaker: "legal",
    brawl: "not_legal",
    historicbrawl: "legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["arena", "paper", "mtgo"],
  reserved: false,
  foil: true,
  nonfoil: true,
  finishes: ["nonfoil", "foil"],
  oversized: false,
  promo: false,
  reprint: false,
  variation: false,
  set_id: "541c3c28-8747-40e5-a231-8e8f33234859",
  set: "stx",
  set_name: "Strixhaven: School of Mages",
  set_type: "expansion",
  set_uri: "https://api.scryfall.com/sets/541c3c28-8747-40e5-a231-8e8f33234859",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Astx&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/stx?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/938cee8f-ac2c-49a5-9ff7-1367d0edfabe/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Ab0907441-30fe-436a-b29c-585b57eabfc3&unique=prints",
  collector_number: "158",
  digital: false,
  rarity: "rare",
  artist: "Yongjae Choi",
  artist_ids: ["5ab91c3b-a6da-4751-a56e-81d0f61a67ab"],
  border_color: "black",
  frame: "2015",
  frame_effects: ["legendary"],
  security_stamp: "oval",
  full_art: false,
  textless: false,
  booster: true,
  story_spotlight: false,
  edhrec_rank: 5868,
  penny_rank: 5582,
  preview: {
    source: "Wizards of the Coast",
    source_uri: "",
    previewed_at: "2021-03-26",
  },
  prices: {
    usd: "0.13",
    usd_foil: "0.28",
    usd_etched: null,
    eur: "0.44",
    eur_foil: "0.50",
    tix: "0.02",
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=513646",
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Shaile%2C+Dean+of+Radiance+%2F%2F+Embrose%2C+Dean+of+Shadow&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Shaile%2C+Dean+of+Radiance+%2F%2F+Embrose%2C+Dean+of+Shadow&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Shaile%2C+Dean+of+Radiance",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/product/235204?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Shaile%2C+Dean+of+Radiance&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards/88815?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
