import { ScryfallCard } from "../../../Card";

const Druid: ScryfallCard.Class = {
  object: "card",
  id: "09278e95-eaae-4cd4-a0d8-a2d15b0abb58",
  oracle_id: "dcbcbf42-4654-487a-acad-21f2606d229b",
  multiverse_ids: [527467],
  mtgo_id: 91862,
  arena_id: 77285,
  tcgplayer_id: 243352,
  cardmarket_id: 571533,
  name: "Druid Class",
  lang: "en",
  released_at: "2021-07-23",
  uri: "https://api.scryfall.com/cards/09278e95-eaae-4cd4-a0d8-a2d15b0abb58",
  scryfall_uri: "https://scryfall.com/card/afr/180/druid-class?utm_source=api",
  layout: "class",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/0/9/09278e95-eaae-4cd4-a0d8-a2d15b0abb58.jpg?1665822447",
    normal: "https://cards.scryfall.io/normal/front/0/9/09278e95-eaae-4cd4-a0d8-a2d15b0abb58.jpg?1665822447",
    large: "https://cards.scryfall.io/large/front/0/9/09278e95-eaae-4cd4-a0d8-a2d15b0abb58.jpg?1665822447",
    png: "https://cards.scryfall.io/png/front/0/9/09278e95-eaae-4cd4-a0d8-a2d15b0abb58.png?1665822447",
    art_crop: "https://cards.scryfall.io/art_crop/front/0/9/09278e95-eaae-4cd4-a0d8-a2d15b0abb58.jpg?1665822447",
    border_crop: "https://cards.scryfall.io/border_crop/front/0/9/09278e95-eaae-4cd4-a0d8-a2d15b0abb58.jpg?1665822447",
  },
  mana_cost: "{1}{G}",
  cmc: 2.0,
  type_line: "Enchantment — Class",
  oracle_text:
    "(Gain the next level as a sorcery to add its ability.)\nLandfall — Whenever a land enters the battlefield under your control, you gain 1 life.\n{2}{G}: Level 2\nYou may play an additional land on each of your turns.\n{4}{G}: Level 3\nWhen this Class becomes level 3, target land you control becomes a creature with haste and \"This creature's power and toughness are each equal to the number of lands you control.\" It's still a land.",
  colors: ["G"],
  color_identity: ["G"],
  keywords: ["Landfall"],
  all_parts: [
    {
      object: "related_card",
      id: "8cbd3554-0096-470d-ba9d-011f5c8212c4",
      component: "combo_piece",
      name: "A-Druid Class",
      type_line: "Enchantment — Class",
      uri: "https://api.scryfall.com/cards/8cbd3554-0096-470d-ba9d-011f5c8212c4",
    },
    {
      object: "related_card",
      id: "09278e95-eaae-4cd4-a0d8-a2d15b0abb58",
      component: "combo_piece",
      name: "Druid Class",
      type_line: "Enchantment — Class",
      uri: "https://api.scryfall.com/cards/09278e95-eaae-4cd4-a0d8-a2d15b0abb58",
    },
  ],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "not_legal",
    gladiator: "legal",
    pioneer: "legal",
    explorer: "legal",
    modern: "legal",
    legacy: "legal",
    pauper: "not_legal",
    vintage: "legal",
    penny: "not_legal",
    commander: "legal",
    oathbreaker: "legal",
    brawl: "not_legal",
    historicbrawl: "not_legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["arena", "paper", "mtgo"],
  reserved: false,
  foil: true,
  nonfoil: true,
  finishes: ["nonfoil", "foil"],
  oversized: false,
  promo: false,
  reprint: false,
  variation: false,
  set_id: "e1ef87ba-ba92-4573-817f-543b996d2851",
  set: "afr",
  set_name: "Adventures in the Forgotten Realms",
  set_type: "expansion",
  set_uri: "https://api.scryfall.com/sets/e1ef87ba-ba92-4573-817f-543b996d2851",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aafr&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/afr?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/09278e95-eaae-4cd4-a0d8-a2d15b0abb58/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Adcbcbf42-4654-487a-acad-21f2606d229b&unique=prints",
  collector_number: "180",
  digital: false,
  rarity: "uncommon",
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "Svetlin Velinov",
  artist_ids: ["ffd063ae-c097-4f26-b2e6-b1e2137708bc"],
  illustration_id: "00e3f921-1d98-4249-81ef-cc42153154cb",
  border_color: "black",
  frame: "2015",
  full_art: false,
  textless: false,
  booster: true,
  story_spotlight: false,
  edhrec_rank: 1038,
  penny_rank: 2220,
  preview: {
    source: "TheAsianAvenger",
    source_uri: "https://twitter.com/Theasianavenger/status/1411030546700902402",
    previewed_at: "2021-07-02",
  },
  prices: {
    usd: "0.64",
    usd_foil: "5.86",
    usd_etched: null,
    eur: "0.87",
    eur_foil: "1.49",
    tix: "0.03",
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=527467",
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Druid+Class&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Druid+Class&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Druid+Class",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/product/243352?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Druid+Class&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards/91862?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
