import { ScryfallCard } from "src";

// White border
const HymnToTourach: ScryfallCard.Normal = {
  object: "card",
  id: "57315f88-6cc5-4b1c-b56e-c8cdbc04f1a1",
  oracle_id: "992d9a72-d34d-47d7-96fb-37f0efb515ef",
  multiverse_ids: [],
  tcgplayer_id: 79551,
  cardmarket_id: 16579,
  name: "Hymn to Tourach",
  lang: "en",
  released_at: "1998-11-01",
  uri: "https://api.scryfall.com/cards/57315f88-6cc5-4b1c-b56e-c8cdbc04f1a1",
  scryfall_uri: "https://scryfall.com/card/ath/23/hymn-to-tourach?utm_source=api",
  layout: "normal",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/5/7/57315f88-6cc5-4b1c-b56e-c8cdbc04f1a1.jpg?1562484796",
    normal: "https://cards.scryfall.io/normal/front/5/7/57315f88-6cc5-4b1c-b56e-c8cdbc04f1a1.jpg?1562484796",
    large: "https://cards.scryfall.io/large/front/5/7/57315f88-6cc5-4b1c-b56e-c8cdbc04f1a1.jpg?1562484796",
    png: "https://cards.scryfall.io/png/front/5/7/57315f88-6cc5-4b1c-b56e-c8cdbc04f1a1.png?1562484796",
    art_crop: "https://cards.scryfall.io/art_crop/front/5/7/57315f88-6cc5-4b1c-b56e-c8cdbc04f1a1.jpg?1562484796",
    border_crop: "https://cards.scryfall.io/border_crop/front/5/7/57315f88-6cc5-4b1c-b56e-c8cdbc04f1a1.jpg?1562484796",
  },
  mana_cost: "{B}{B}",
  cmc: 2.0,
  type_line: "Sorcery",
  oracle_text: "Target player discards two cards at random.",
  colors: ["B"],
  color_identity: ["B"],
  keywords: [],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "not_legal",
    gladiator: "not_legal",
    pioneer: "not_legal",
    explorer: "not_legal",
    modern: "not_legal",
    legacy: "legal",
    pauper: "banned",
    vintage: "legal",
    penny: "not_legal",
    commander: "legal",
    oathbreaker: "legal",
    brawl: "not_legal",
    historicbrawl: "not_legal",
    alchemy: "not_legal",
    paupercommander: "legal",
    duel: "legal",
    oldschool: "legal",
    premodern: "not_legal",
    predh: "legal",
  },
  games: ["paper"],
  reserved: false,
  foil: false,
  nonfoil: true,
  finishes: ["nonfoil"],
  oversized: false,
  promo: false,
  reprint: true,
  variation: false,
  set_id: "49c9409d-5948-4c00-bd0a-bf3ebd50e23a",
  set: "ath",
  set_name: "Anthologies",
  set_type: "box",
  set_uri: "https://api.scryfall.com/sets/49c9409d-5948-4c00-bd0a-bf3ebd50e23a",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aath&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/ath?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/57315f88-6cc5-4b1c-b56e-c8cdbc04f1a1/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A992d9a72-d34d-47d7-96fb-37f0efb515ef&unique=prints",
  collector_number: "23",
  digital: false,
  rarity: "common",
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "Liz Danforth",
  artist_ids: ["5a5ee217-9d28-419a-b92a-a2376c7d18b3"],
  illustration_id: "55860add-12cc-4fed-9176-427b1cd2f85b",
  border_color: "white",
  frame: "1997",
  full_art: false,
  textless: false,
  booster: false,
  story_spotlight: false,
  edhrec_rank: 6762,
  penny_rank: 12,
  prices: {
    usd: "1.27",
    usd_foil: null,
    usd_etched: null,
    eur: "0.99",
    eur_foil: null,
    tix: null,
  },
  related_uris: {
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Hymn+to+Tourach&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Hymn+to+Tourach&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Hymn+to+Tourach",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/product/79551?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Hymn+to+Tourach&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Hymn+to+Tourach&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
