import { ScryfallCard } from "src";

const BeanstalkGiant: ScryfallCard.Adventure = {
  object: "card",
  id: "dfd6b4bc-70da-4d93-bdf7-78ba176a764f",
  oracle_id: "22c75ad5-237c-4dbd-bbc4-3058a3db408f",
  multiverse_ids: [627739],
  mtgo_id: 114777,
  tcgplayer_id: 507111,
  cardmarket_id: 723509,
  name: "Beanstalk Giant // Fertile Footsteps",
  lang: "en",
  released_at: "2023-08-04",
  uri: "https://api.scryfall.com/cards/dfd6b4bc-70da-4d93-bdf7-78ba176a764f",
  scryfall_uri: "https://scryfall.com/card/cmm/275/beanstalk-giant-fertile-footsteps?utm_source=api",
  layout: "adventure",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/d/f/dfd6b4bc-70da-4d93-bdf7-78ba176a764f.jpg?1691058368",
    normal: "https://cards.scryfall.io/normal/front/d/f/dfd6b4bc-70da-4d93-bdf7-78ba176a764f.jpg?1691058368",
    large: "https://cards.scryfall.io/large/front/d/f/dfd6b4bc-70da-4d93-bdf7-78ba176a764f.jpg?1691058368",
    png: "https://cards.scryfall.io/png/front/d/f/dfd6b4bc-70da-4d93-bdf7-78ba176a764f.png?1691058368",
    art_crop: "https://cards.scryfall.io/art_crop/front/d/f/dfd6b4bc-70da-4d93-bdf7-78ba176a764f.jpg?1691058368",
    border_crop: "https://cards.scryfall.io/border_crop/front/d/f/dfd6b4bc-70da-4d93-bdf7-78ba176a764f.jpg?1691058368",
  },
  mana_cost: "{6}{G} // {2}{G}",
  cmc: 7.0,
  type_line: "Creature — Giant // Sorcery — Adventure",
  power: "*",
  toughness: "*",
  colors: ["G"],
  color_identity: ["G"],
  keywords: [],
  card_faces: [
    {
      object: "card_face",
      name: "Beanstalk Giant",
      mana_cost: "{6}{G}",
      type_line: "Creature — Giant",
      oracle_text: "Beanstalk Giant's power and toughness are each equal to the number of lands you control.",
      power: "*",
      toughness: "*",
      artist: "Jason A. Engle",
      artist_id: "02e2b5de-4341-464c-8fdb-a1adbf873bc0",
      illustration_id: "45c422bc-0d57-4909-b5f1-8d2873b5861a",
    },
    {
      object: "card_face",
      name: "Fertile Footsteps",
      flavor_name: "",
      mana_cost: "{2}{G}",
      type_line: "Sorcery — Adventure",
      oracle_text:
        "Search your library for a basic land card, put it onto the battlefield, then shuffle. (Then exile this card. You may cast the creature later from exile.)",
      artist: "Jason A. Engle",
      artist_id: "02e2b5de-4341-464c-8fdb-a1adbf873bc0",
    },
  ],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "legal",
    gladiator: "legal",
    pioneer: "legal",
    explorer: "legal",
    modern: "legal",
    legacy: "legal",
    pauper: "not_legal",
    vintage: "legal",
    penny: "not_legal",
    commander: "legal",
    oathbreaker: "legal",
    brawl: "not_legal",
    historicbrawl: "legal",
    alchemy: "not_legal",
    paupercommander: "restricted",
    duel: "legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["paper", "mtgo"],
  reserved: false,
  foil: true,
  nonfoil: true,
  finishes: ["nonfoil", "foil"],
  oversized: false,
  promo: false,
  reprint: true,
  variation: false,
  set_id: "cd05036f-2698-43e6-a48e-5c8d82f0a551",
  set: "cmm",
  set_name: "Commander Masters",
  set_type: "masters",
  set_uri: "https://api.scryfall.com/sets/cd05036f-2698-43e6-a48e-5c8d82f0a551",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Acmm&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/cmm?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/dfd6b4bc-70da-4d93-bdf7-78ba176a764f/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A22c75ad5-237c-4dbd-bbc4-3058a3db408f&unique=prints",
  collector_number: "275",
  digital: false,
  rarity: "uncommon",
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "Jason A. Engle",
  artist_ids: ["02e2b5de-4341-464c-8fdb-a1adbf873bc0"],
  illustration_id: "45c422bc-0d57-4909-b5f1-8d2873b5861a",
  border_color: "black",
  frame: "2015",
  full_art: false,
  textless: false,
  booster: true,
  story_spotlight: false,
  edhrec_rank: 1523,
  penny_rank: 1856,
  prices: {
    usd: "0.14",
    usd_foil: "0.16",
    usd_etched: null,
    eur: "0.15",
    eur_foil: "0.10",
    tix: "0.04",
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=627739",
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Beanstalk+Giant+%2F%2F+Fertile+Footsteps&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Beanstalk+Giant+%2F%2F+Fertile+Footsteps&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Beanstalk+Giant",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/product/507111?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Beanstalk+Giant&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards/114777?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
