import { ScryfallCard } from "src";

// Land creature
const DryadArbor: TestCard<ScryfallCard.Normal> = {
  object: "card",
  id: "bb3a843b-2dea-4b44-be74-c09c18b9b969",
  oracle_id: "e996cd67-739c-40f4-b276-0042acf26c71",
  multiverse_ids: [509642],
  mtgo_id: 86929,
  tcgplayer_id: 234111,
  cardmarket_id: 547706,
  name: "Dryad Arbor",
  lang: "en",
  released_at: "2021-03-19",
  uri: "https://api.scryfall.com/cards/bb3a843b-2dea-4b44-be74-c09c18b9b969",
  scryfall_uri: "https://scryfall.com/card/tsr/277/dryad-arbor?utm_source=api",
  layout: "normal",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/b/b/bb3a843b-2dea-4b44-be74-c09c18b9b969.jpg?1619399228",
    normal: "https://cards.scryfall.io/normal/front/b/b/bb3a843b-2dea-4b44-be74-c09c18b9b969.jpg?1619399228",
    large: "https://cards.scryfall.io/large/front/b/b/bb3a843b-2dea-4b44-be74-c09c18b9b969.jpg?1619399228",
    png: "https://cards.scryfall.io/png/front/b/b/bb3a843b-2dea-4b44-be74-c09c18b9b969.png?1619399228",
    art_crop: "https://cards.scryfall.io/art_crop/front/b/b/bb3a843b-2dea-4b44-be74-c09c18b9b969.jpg?1619399228",
    border_crop: "https://cards.scryfall.io/border_crop/front/b/b/bb3a843b-2dea-4b44-be74-c09c18b9b969.jpg?1619399228",
  },
  mana_cost: "",
  cmc: 0.0,
  type_line: "Land Creature — Forest Dryad",
  oracle_text: "(Dryad Arbor isn't a spell, it's affected by summoning sickness, and it has \"{T}: Add {G}.\")",
  power: "1",
  toughness: "1",
  colors: ["G"],
  color_indicator: ["G"],
  color_identity: ["G"],
  keywords: [],
  produced_mana: ["G"],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "not_legal",
    gladiator: "not_legal",
    pioneer: "not_legal",
    explorer: "not_legal",
    modern: "legal",
    legacy: "legal",
    pauper: "not_legal",
    vintage: "legal",
    penny: "not_legal",
    commander: "legal",
    oathbreaker: "legal",
    brawl: "not_legal",
    historicbrawl: "not_legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "legal",
  },
  games: ["paper", "mtgo"],
  reserved: false,
  foil: true,
  nonfoil: true,
  finishes: ["nonfoil", "foil"],
  oversized: false,
  promo: false,
  reprint: true,
  variation: false,
  set_id: "11e90d1b-0502-43e6-b056-e24836523c13",
  set: "tsr",
  set_name: "Time Spiral Remastered",
  set_type: "masters",
  set_uri: "https://api.scryfall.com/sets/11e90d1b-0502-43e6-b056-e24836523c13",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Atsr&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/tsr?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/bb3a843b-2dea-4b44-be74-c09c18b9b969/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Ae996cd67-739c-40f4-b276-0042acf26c71&unique=prints",
  collector_number: "277",
  digital: false,
  rarity: "rare",
  flavor_text:
    '"Touch no tree, break no branch, and speak only the question you wish answered."\n—Von Yomm, elder druid, to her initiates',
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "Eric Fortune",
  artist_ids: ["c5562592-3387-495a-96fb-618a6a424a45"],
  illustration_id: "80a2053e-3199-4ff4-968c-a3d30b419afa",
  border_color: "black",
  frame: "2015",
  security_stamp: "oval",
  full_art: false,
  textless: false,
  booster: true,
  story_spotlight: false,
  edhrec_rank: 645,
  preview: {
    source: "Simone Trimarchi",
    source_uri: "https://twitter.com/SimoneAKirA/status/1367444976804777984",
    previewed_at: "2021-03-04",
  },
  prices: {
    usd: "3.62",
    usd_foil: "10.38",
    usd_etched: null,
    eur: "2.42",
    eur_foil: "7.48",
    tix: "0.52",
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=509642",
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Dryad+Arbor&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Dryad+Arbor&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Dryad+Arbor",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/product/234111?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Dryad+Arbor&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards/86929?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
const DryadArbor_Unknown: ScryfallCard.Unknown = DryadArbor;
