import { ScryfallCard } from "src";

const LlanowarElves: TestCard<ScryfallCard.Normal> = {
  object: "card",
  id: "d4f1cc9e-4f99-4c26-ac1b-8ef069fa8ceb",
  oracle_id: "68954295-54e3-4303-a6bc-fc4547a4e3a3",
  multiverse_ids: [166],
  tcgplayer_id: 1178,
  cardmarket_id: 5352,
  name: "Llanowar Elves",
  lang: "en",
  released_at: "1993-08-05",
  uri: "https://api.scryfall.com/cards/d4f1cc9e-4f99-4c26-ac1b-8ef069fa8ceb",
  scryfall_uri: "https://scryfall.com/card/lea/210/llanowar-elves?utm_source=api",
  layout: "normal",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/d/4/d4f1cc9e-4f99-4c26-ac1b-8ef069fa8ceb.jpg?1559591371",
    normal: "https://cards.scryfall.io/normal/front/d/4/d4f1cc9e-4f99-4c26-ac1b-8ef069fa8ceb.jpg?1559591371",
    large: "https://cards.scryfall.io/large/front/d/4/d4f1cc9e-4f99-4c26-ac1b-8ef069fa8ceb.jpg?1559591371",
    png: "https://cards.scryfall.io/png/front/d/4/d4f1cc9e-4f99-4c26-ac1b-8ef069fa8ceb.png?1559591371",
    art_crop: "https://cards.scryfall.io/art_crop/front/d/4/d4f1cc9e-4f99-4c26-ac1b-8ef069fa8ceb.jpg?1559591371",
    border_crop: "https://cards.scryfall.io/border_crop/front/d/4/d4f1cc9e-4f99-4c26-ac1b-8ef069fa8ceb.jpg?1559591371",
  },
  mana_cost: "{G}",
  cmc: 1.0,
  type_line: "Creature — Elf Druid",
  oracle_text: "{T}: Add {G}.",
  power: "1",
  toughness: "1",
  colors: ["G"],
  color_identity: ["G"],
  keywords: [],
  produced_mana: ["G"],
  all_parts: [
    {
      object: "related_card",
      id: "d4f1cc9e-4f99-4c26-ac1b-8ef069fa8ceb",
      component: "combo_piece",
      name: "Llanowar Elves",
      type_line: "Creature — Elf Druid",
      uri: "https://api.scryfall.com/cards/d4f1cc9e-4f99-4c26-ac1b-8ef069fa8ceb",
    },
    {
      object: "related_card",
      id: "8ef95e7a-9f07-41f8-908b-2df93e03d391",
      component: "combo_piece",
      name: "Marwyn's Kindred",
      type_line: "Sorcery",
      uri: "https://api.scryfall.com/cards/8ef95e7a-9f07-41f8-908b-2df93e03d391",
    },
  ],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "legal",
    gladiator: "legal",
    pioneer: "legal",
    explorer: "legal",
    modern: "legal",
    legacy: "legal",
    pauper: "legal",
    vintage: "legal",
    penny: "legal",
    commander: "legal",
    oathbreaker: "legal",
    brawl: "not_legal",
    historicbrawl: "legal",
    alchemy: "not_legal",
    paupercommander: "legal",
    duel: "legal",
    oldschool: "legal",
    premodern: "legal",
    predh: "legal",
  },
  games: ["paper"],
  reserved: false,
  foil: false,
  nonfoil: true,
  finishes: ["nonfoil"],
  oversized: false,
  promo: false,
  reprint: false,
  variation: false,
  set_id: "288bd996-960e-448b-a187-9504c1930c2c",
  set: "lea",
  set_name: "Limited Edition Alpha",
  set_type: "core",
  set_uri: "https://api.scryfall.com/sets/288bd996-960e-448b-a187-9504c1930c2c",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Alea&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/lea?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/d4f1cc9e-4f99-4c26-ac1b-8ef069fa8ceb/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A68954295-54e3-4303-a6bc-fc4547a4e3a3&unique=prints",
  collector_number: "210",
  digital: false,
  rarity: "common",
  flavor_text:
    "Whenever the Llanowar Elves gather the fruits of their forest, they leave one plant of each type untouched, considering that nature's portion.",
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "Anson Maddocks",
  artist_ids: ["634430a7-b5c3-4e4a-b2ac-164e084e47c9"],
  illustration_id: "0593112b-9ba0-4524-a853-52f954cd60f1",
  border_color: "black",
  frame: "1993",
  full_art: false,
  textless: false,
  booster: true,
  story_spotlight: false,
  edhrec_rank: 58,
  penny_rank: 155,
  prices: {
    usd: "339.98",
    usd_foil: null,
    usd_etched: null,
    eur: "399.95",
    eur_foil: null,
    tix: null,
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=166",
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Llanowar+Elves&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Llanowar+Elves&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Llanowar+Elves",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/product/1178?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Llanowar+Elves&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Llanowar+Elves&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
