import { ScryfallCard } from "../../../Card";

const InvertAndInvent: ScryfallCard.Split = {
  object: "card",
  id: "054a4e4f-8baa-41cf-b24c-d068e8b9a070",
  oracle_id: "9a378964-2c04-4d60-a905-c819d37ed4c3",
  multiverse_ids: [452978],
  mtgo_id: 69861,
  arena_id: 68703,
  tcgplayer_id: 176560,
  cardmarket_id: 364053,
  name: "Invert // Invent",
  lang: "en",
  released_at: "2018-10-05",
  uri: "https://api.scryfall.com/cards/054a4e4f-8baa-41cf-b24c-d068e8b9a070",
  scryfall_uri: "https://scryfall.com/card/grn/228/invert-invent?utm_source=api",
  layout: "split",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/0/5/054a4e4f-8baa-41cf-b24c-d068e8b9a070.jpg?1665155918",
    normal: "https://cards.scryfall.io/normal/front/0/5/054a4e4f-8baa-41cf-b24c-d068e8b9a070.jpg?1665155918",
    large: "https://cards.scryfall.io/large/front/0/5/054a4e4f-8baa-41cf-b24c-d068e8b9a070.jpg?1665155918",
    png: "https://cards.scryfall.io/png/front/0/5/054a4e4f-8baa-41cf-b24c-d068e8b9a070.png?1665155918",
    art_crop: "https://cards.scryfall.io/art_crop/front/0/5/054a4e4f-8baa-41cf-b24c-d068e8b9a070.jpg?1665155918",
    border_crop: "https://cards.scryfall.io/border_crop/front/0/5/054a4e4f-8baa-41cf-b24c-d068e8b9a070.jpg?1665155918",
  },
  mana_cost: "{U/R} // {4}{U}{R}",
  cmc: 7,
  type_line: "Instant // Instant",
  colors: ["R", "U"],
  color_identity: ["R", "U"],
  keywords: [],
  card_faces: [
    {
      object: "card_face",
      name: "Invert",
      mana_cost: "{U/R}",
      type_line: "Instant",
      oracle_text: "Switch the power and toughness of each of up to two target creatures until end of turn.",
      watermark: "izzet",
      artist: "Mathias Kollros",
      artist_id: "2ae0dd12-047c-4efb-80d7-bccc3bac5fba",
      illustration_id: "154c4b3a-2222-4e11-9507-4486828208b6",
    },
    {
      object: "card_face",
      name: "Invent",
      flavor_name: "",
      mana_cost: "{4}{U}{R}",
      type_line: "Instant",
      oracle_text:
        "Search your library for an instant card and/or a sorcery card, reveal them, put them into your hand, then shuffle.",
      watermark: "izzet",
      artist: "Mathias Kollros",
      artist_id: "2ae0dd12-047c-4efb-80d7-bccc3bac5fba",
    },
  ],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "legal",
    gladiator: "legal",
    pioneer: "legal",
    explorer: "legal",
    modern: "legal",
    legacy: "legal",
    pauper: "not_legal",
    vintage: "legal",
    penny: "not_legal",
    commander: "legal",
    oathbreaker: "legal",
    brawl: "not_legal",
    historicbrawl: "legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["arena", "paper", "mtgo"],
  reserved: false,
  foil: true,
  nonfoil: true,
  finishes: ["nonfoil", "foil"],
  oversized: false,
  promo: false,
  reprint: false,
  variation: false,
  set_id: "597c6d4a-8212-4903-a6af-12c4ae9e13f0",
  set: "grn",
  set_name: "Guilds of Ravnica",
  set_type: "expansion",
  set_uri: "https://api.scryfall.com/sets/597c6d4a-8212-4903-a6af-12c4ae9e13f0",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Agrn&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/grn?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/054a4e4f-8baa-41cf-b24c-d068e8b9a070/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A9a378964-2c04-4d60-a905-c819d37ed4c3&unique=prints",
  collector_number: "228",
  digital: false,
  rarity: "uncommon",
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "Mathias Kollros",
  artist_ids: ["2ae0dd12-047c-4efb-80d7-bccc3bac5fba"],
  illustration_id: "154c4b3a-2222-4e11-9507-4486828208b6",
  border_color: "black",
  frame: "2015",
  full_art: false,
  textless: false,
  booster: true,
  story_spotlight: false,
  edhrec_rank: 8596,
  penny_rank: 8003,
  prices: {
    usd: "0.13",
    usd_foil: "1.49",
    usd_etched: null,
    eur: "0.14",
    eur_foil: "0.25",
    tix: "0.03",
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=452978",
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Invert+%2F%2F+Invent&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Invert+%2F%2F+Invent&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Invert+%2F%2F+Invent",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/product/176560?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Invert+%2F%2F+Invent&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards/69861?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
