import { ScryfallCard } from "../../../Card";

const LifeAndDeath: ScryfallCard.Split = {
  object: "card",
  id: "2424f2c4-366b-42cf-bf4b-a8a5bfdd2c4b",
  oracle_id: "d476f4b3-db63-4756-ab76-4b35f63c2825",
  multiverse_ids: [292976],
  mtgo_id: 46099,
  tcgplayer_id: 66370,
  cardmarket_id: 258172,
  name: "Life // Death",
  lang: "en",
  released_at: "2012-09-07",
  uri: "https://api.scryfall.com/cards/2424f2c4-366b-42cf-bf4b-a8a5bfdd2c4b",
  scryfall_uri: "https://scryfall.com/card/ddj/77/life-death?utm_source=api",
  layout: "split",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/2/4/2424f2c4-366b-42cf-bf4b-a8a5bfdd2c4b.jpg?1592713837",
    normal: "https://cards.scryfall.io/normal/front/2/4/2424f2c4-366b-42cf-bf4b-a8a5bfdd2c4b.jpg?1592713837",
    large: "https://cards.scryfall.io/large/front/2/4/2424f2c4-366b-42cf-bf4b-a8a5bfdd2c4b.jpg?1592713837",
    png: "https://cards.scryfall.io/png/front/2/4/2424f2c4-366b-42cf-bf4b-a8a5bfdd2c4b.png?1592713837",
    art_crop: "https://cards.scryfall.io/art_crop/front/2/4/2424f2c4-366b-42cf-bf4b-a8a5bfdd2c4b.jpg?1592713837",
    border_crop: "https://cards.scryfall.io/border_crop/front/2/4/2424f2c4-366b-42cf-bf4b-a8a5bfdd2c4b.jpg?1592713837",
  },
  mana_cost: "{G} // {1}{B}",
  cmc: 3,
  type_line: "Sorcery // Sorcery",
  colors: ["B", "G"],
  color_identity: ["B", "G"],
  keywords: [],
  card_faces: [
    {
      object: "card_face",
      name: "Life",
      mana_cost: "{G}",
      type_line: "Sorcery",
      oracle_text: "All lands you control become 1/1 creatures until end of turn. They're still lands.",
      artist: "Ryan Barger",
      artist_id: "a4e0102e-bbeb-497c-babc-1c0741fea914",
      illustration_id: "c369060c-3d6e-41cf-abcb-21e26205be37",
    },
    {
      object: "card_face",
      name: "Death",
      flavor_name: "",
      mana_cost: "{1}{B}",
      type_line: "Sorcery",
      oracle_text:
        "Return target creature card from your graveyard to the battlefield. You lose life equal to its mana value.",
      artist: "Ryan Barger",
      artist_id: "a4e0102e-bbeb-497c-babc-1c0741fea914",
    },
  ],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "not_legal",
    gladiator: "not_legal",
    pioneer: "not_legal",
    explorer: "not_legal",
    modern: "not_legal",
    legacy: "legal",
    pauper: "not_legal",
    vintage: "legal",
    penny: "not_legal",
    commander: "legal",
    oathbreaker: "legal",
    brawl: "not_legal",
    historicbrawl: "not_legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "legal",
    oldschool: "not_legal",
    premodern: "legal",
    predh: "legal",
  },
  games: ["paper", "mtgo"],
  reserved: false,
  foil: false,
  nonfoil: true,
  finishes: ["nonfoil"],
  oversized: false,
  promo: false,
  reprint: true,
  variation: false,
  set_id: "2dfea68b-b0c4-4f63-ba6c-36c9a6e3030f",
  set: "ddj",
  set_name: "Duel Decks: Izzet vs. Golgari",
  set_type: "duel_deck",
  set_uri: "https://api.scryfall.com/sets/2dfea68b-b0c4-4f63-ba6c-36c9a6e3030f",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Addj&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/ddj?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/2424f2c4-366b-42cf-bf4b-a8a5bfdd2c4b/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Ad476f4b3-db63-4756-ab76-4b35f63c2825&unique=prints",
  collector_number: "77",
  digital: false,
  rarity: "uncommon",
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "Ryan Barger",
  artist_ids: ["a4e0102e-bbeb-497c-babc-1c0741fea914"],
  illustration_id: "c369060c-3d6e-41cf-abcb-21e26205be37",
  border_color: "black",
  frame: "2003",
  full_art: false,
  textless: false,
  booster: false,
  story_spotlight: false,
  edhrec_rank: 3693,
  penny_rank: 220,
  prices: {
    usd: "0.82",
    usd_foil: null,
    usd_etched: null,
    eur: "0.55",
    eur_foil: null,
    tix: "0.47",
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=292976",
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Life+%2F%2F+Death&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Life+%2F%2F+Death&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Life+%2F%2F+Death",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/product/66370?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Life+%2F%2F+Death&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards/46099?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
