import { ScryfallCard } from "src";

const InvasionOfIkoria: TestCard<ScryfallCard.Transform> = {
  object: "card",
  id: "5d59c8f2-f6af-40a6-8dfe-8cc45bf231ce",
  oracle_id: "21d90735-5e04-4a8c-a546-ff26d4d5998d",
  multiverse_ids: [607241, 607242],
  mtgo_id: 110254,
  arena_id: 84477,
  tcgplayer_id: 490335,
  cardmarket_id: 704045,
  name: "Invasion of Ikoria // Zilortha, Apex of Ikoria",
  lang: "en",
  released_at: "2023-04-21",
  uri: "https://api.scryfall.com/cards/5d59c8f2-f6af-40a6-8dfe-8cc45bf231ce",
  scryfall_uri: "https://scryfall.com/card/mom/190/invasion-of-ikoria-zilortha-apex-of-ikoria?utm_source=api",
  layout: "transform",
  highres_image: true,
  image_status: "highres_scan",
  cmc: 2.0,
  type_line: "Battle — Siege // Legendary Creature — Dinosaur",
  color_identity: ["G"],
  keywords: ["Reach", "Transform"],
  card_faces: [
    {
      object: "card_face",
      name: "Invasion of Ikoria",
      mana_cost: "{X}{G}{G}",
      type_line: "Battle — Siege",
      oracle_text:
        "(As a Siege enters, choose an opponent to protect it. You and others can attack it. When it's defeated, exile it, then cast it transformed.)\nWhen Invasion of Ikoria enters the battlefield, search your library and/or graveyard for a non-Human creature card with mana value X or less and put it onto the battlefield. If you search your library this way, shuffle.",
      colors: ["G"],
      defense: "6",
      artist: "Antonio José Manzanedo",
      artist_id: "74986d28-0001-4a78-827c-e490b325d0e3",
      illustration_id: "4e5a5dbe-5ae7-47c3-83fe-1e2ef7c255e5",
      image_uris: {
        small: "https://cards.scryfall.io/small/front/5/d/5d59c8f2-f6af-40a6-8dfe-8cc45bf231ce.jpg?1682715265",
        normal: "https://cards.scryfall.io/normal/front/5/d/5d59c8f2-f6af-40a6-8dfe-8cc45bf231ce.jpg?1682715265",
        large: "https://cards.scryfall.io/large/front/5/d/5d59c8f2-f6af-40a6-8dfe-8cc45bf231ce.jpg?1682715265",
        png: "https://cards.scryfall.io/png/front/5/d/5d59c8f2-f6af-40a6-8dfe-8cc45bf231ce.png?1682715265",
        art_crop: "https://cards.scryfall.io/art_crop/front/5/d/5d59c8f2-f6af-40a6-8dfe-8cc45bf231ce.jpg?1682715265",
        border_crop:
          "https://cards.scryfall.io/border_crop/front/5/d/5d59c8f2-f6af-40a6-8dfe-8cc45bf231ce.jpg?1682715265",
      },
    },
    {
      object: "card_face",
      name: "Zilortha, Apex of Ikoria",
      flavor_name: "",
      mana_cost: "",
      type_line: "Legendary Creature — Dinosaur",
      oracle_text:
        "Reach\nFor each non-Human creature you control, you may have that creature assign its combat damage as though it weren't blocked.",
      colors: ["G"],
      color_indicator: ["G"],
      power: "8",
      toughness: "8",
      flavor_text:
        "Phyrexia's largest goliaths stormed Ikoria, ready to challenge the world's great monsters. Zilortha was unimpressed.",
      artist: "Antonio José Manzanedo",
      artist_id: "74986d28-0001-4a78-827c-e490b325d0e3",
      illustration_id: "c5e54496-d13e-47be-a71c-68b6ea3f107a",
      image_uris: {
        small: "https://cards.scryfall.io/small/back/5/d/5d59c8f2-f6af-40a6-8dfe-8cc45bf231ce.jpg?1682715265",
        normal: "https://cards.scryfall.io/normal/back/5/d/5d59c8f2-f6af-40a6-8dfe-8cc45bf231ce.jpg?1682715265",
        large: "https://cards.scryfall.io/large/back/5/d/5d59c8f2-f6af-40a6-8dfe-8cc45bf231ce.jpg?1682715265",
        png: "https://cards.scryfall.io/png/back/5/d/5d59c8f2-f6af-40a6-8dfe-8cc45bf231ce.png?1682715265",
        art_crop: "https://cards.scryfall.io/art_crop/back/5/d/5d59c8f2-f6af-40a6-8dfe-8cc45bf231ce.jpg?1682715265",
        border_crop:
          "https://cards.scryfall.io/border_crop/back/5/d/5d59c8f2-f6af-40a6-8dfe-8cc45bf231ce.jpg?1682715265",
      },
    },
  ],
  legalities: {
    standard: "legal",
    future: "legal",
    historic: "legal",
    gladiator: "legal",
    pioneer: "legal",
    explorer: "legal",
    modern: "legal",
    legacy: "legal",
    pauper: "not_legal",
    vintage: "legal",
    penny: "not_legal",
    commander: "legal",
    oathbreaker: "legal",
    brawl: "legal",
    historicbrawl: "legal",
    alchemy: "legal",
    paupercommander: "not_legal",
    duel: "legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["paper", "mtgo", "arena"],
  reserved: false,
  foil: true,
  nonfoil: true,
  finishes: ["nonfoil", "foil"],
  oversized: false,
  promo: false,
  reprint: false,
  variation: false,
  set_id: "392f7315-dc53-40a3-a2cc-5482dbd498b3",
  set: "mom",
  set_name: "March of the Machine",
  set_type: "expansion",
  set_uri: "https://api.scryfall.com/sets/392f7315-dc53-40a3-a2cc-5482dbd498b3",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Amom&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/mom?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/5d59c8f2-f6af-40a6-8dfe-8cc45bf231ce/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A21d90735-5e04-4a8c-a546-ff26d4d5998d&unique=prints",
  collector_number: "190",
  digital: false,
  rarity: "rare",
  artist: "Antonio José Manzanedo",
  artist_ids: ["74986d28-0001-4a78-827c-e490b325d0e3"],
  border_color: "black",
  frame: "2015",
  frame_effects: ["legendary"],
  security_stamp: "oval",
  full_art: false,
  textless: false,
  booster: true,
  story_spotlight: false,
  edhrec_rank: 1983,
  prices: {
    usd: "6.06",
    usd_foil: "8.11",
    usd_etched: null,
    eur: "5.90",
    eur_foil: "10.18",
    tix: "0.52",
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=607241",
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Invasion+of+Ikoria+%2F%2F+Zilortha%2C+Apex+of+Ikoria&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Invasion+of+Ikoria+%2F%2F+Zilortha%2C+Apex+of+Ikoria&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Invasion+of+Ikoria",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/product/490335?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Invasion+of+Ikoria&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards/110254?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
