import { ScryfallCard } from "src";

const Narset: TestCard<ScryfallCard.Emblem> = {
  object: "card",
  id: "4a70dfe0-874c-473a-a26e-1f88a842df41",
  oracle_id: "476138f9-67ff-49bf-ac11-2aac20669a1d",
  multiverse_ids: [],
  tcgplayer_id: 96541,
  name: "Narset Transcendent Emblem",
  lang: "en",
  released_at: "2015-03-27",
  uri: "https://api.scryfall.com/cards/4a70dfe0-874c-473a-a26e-1f88a842df41",
  scryfall_uri: "https://scryfall.com/card/tdtk/8/narset-transcendent-emblem?utm_source=api",
  layout: "emblem",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/4/a/4a70dfe0-874c-473a-a26e-1f88a842df41.jpg?1561757075",
    normal: "https://cards.scryfall.io/normal/front/4/a/4a70dfe0-874c-473a-a26e-1f88a842df41.jpg?1561757075",
    large: "https://cards.scryfall.io/large/front/4/a/4a70dfe0-874c-473a-a26e-1f88a842df41.jpg?1561757075",
    png: "https://cards.scryfall.io/png/front/4/a/4a70dfe0-874c-473a-a26e-1f88a842df41.png?1561757075",
    art_crop: "https://cards.scryfall.io/art_crop/front/4/a/4a70dfe0-874c-473a-a26e-1f88a842df41.jpg?1561757075",
    border_crop: "https://cards.scryfall.io/border_crop/front/4/a/4a70dfe0-874c-473a-a26e-1f88a842df41.jpg?1561757075",
  },
  mana_cost: "",
  cmc: 0.0,
  type_line: "Emblem — Narset",
  oracle_text: "Your opponents can't cast noncreature spells.",
  colors: [],
  color_identity: [],
  keywords: [],
  all_parts: [
    {
      object: "related_card",
      id: "4a70dfe0-874c-473a-a26e-1f88a842df41",
      component: "combo_piece",
      name: "Narset Transcendent Emblem",
      type_line: "Emblem — Narset",
      uri: "https://api.scryfall.com/cards/4a70dfe0-874c-473a-a26e-1f88a842df41",
    },
    {
      object: "related_card",
      id: "4816d092-e34b-4397-8599-43d8e85a8f39",
      component: "combo_piece",
      name: "Narset Transcendent",
      type_line: "Legendary Planeswalker — Narset",
      uri: "https://api.scryfall.com/cards/4816d092-e34b-4397-8599-43d8e85a8f39",
    },
  ],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "not_legal",
    gladiator: "not_legal",
    pioneer: "not_legal",
    explorer: "not_legal",
    modern: "not_legal",
    legacy: "not_legal",
    pauper: "not_legal",
    vintage: "not_legal",
    penny: "not_legal",
    commander: "not_legal",
    oathbreaker: "not_legal",
    brawl: "not_legal",
    historicbrawl: "not_legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "not_legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["paper"],
  reserved: false,
  foil: false,
  nonfoil: true,
  finishes: ["nonfoil"],
  oversized: false,
  promo: false,
  reprint: false,
  variation: false,
  set_id: "e9bd9e1e-754a-4d8f-a1d1-b9b6f18474c5",
  set: "tdtk",
  set_name: "Dragons of Tarkir Tokens",
  set_type: "token",
  set_uri: "https://api.scryfall.com/sets/e9bd9e1e-754a-4d8f-a1d1-b9b6f18474c5",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Atdtk&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/tdtk?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/4a70dfe0-874c-473a-a26e-1f88a842df41/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A476138f9-67ff-49bf-ac11-2aac20669a1d&unique=prints",
  collector_number: "8",
  digital: false,
  rarity: "common",
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "Magali Villeneuve",
  artist_ids: ["9e6a55ae-be4d-4c23-a2a5-135737ffd879"],
  illustration_id: "d6050edf-2d95-4812-bc07-2ad8318e1819",
  border_color: "black",
  frame: "2015",
  full_art: false,
  textless: false,
  booster: true,
  story_spotlight: false,
  promo_types: ["setpromo"],
  prices: {
    usd: "2.17",
    usd_foil: null,
    usd_etched: null,
    eur: null,
    eur_foil: null,
    tix: null,
  },
  related_uris: {
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Narset+Transcendent+Emblem&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Narset+Transcendent+Emblem&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Narset+Transcendent+Emblem",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/product/96541?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Narset+Transcendent+Emblem&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Narset+Transcendent+Emblem&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
