import { ScryfallCard } from "../../..";

const FreneticEfreet: ScryfallCard.Vanguard = {
  object: "card",
  id: "3b81d1a1-487d-40b7-88f5-691d2a01dad5",
  oracle_id: "df33f381-ff74-4ef2-8396-443019590006",
  multiverse_ids: [182275],
  mtgo_id: 38,
  name: "Frenetic Efreet Avatar",
  lang: "en",
  released_at: "2003-01-01",
  uri: "https://api.scryfall.com/cards/3b81d1a1-487d-40b7-88f5-691d2a01dad5",
  scryfall_uri: "https://scryfall.com/card/pmoa/53/frenetic-efreet-avatar?utm_source=api",
  layout: "vanguard",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/3/b/3b81d1a1-487d-40b7-88f5-691d2a01dad5.jpg?1562908946",
    normal: "https://cards.scryfall.io/normal/front/3/b/3b81d1a1-487d-40b7-88f5-691d2a01dad5.jpg?1562908946",
    large: "https://cards.scryfall.io/large/front/3/b/3b81d1a1-487d-40b7-88f5-691d2a01dad5.jpg?1562908946",
    png: "https://cards.scryfall.io/png/front/3/b/3b81d1a1-487d-40b7-88f5-691d2a01dad5.png?1562908946",
    art_crop: "https://cards.scryfall.io/art_crop/front/3/b/3b81d1a1-487d-40b7-88f5-691d2a01dad5.jpg?1562908946",
    border_crop: "https://cards.scryfall.io/border_crop/front/3/b/3b81d1a1-487d-40b7-88f5-691d2a01dad5.jpg?1562908946",
  },
  mana_cost: "",
  cmc: 0,
  type_line: "Vanguard",
  oracle_text:
    "Each permanent you control has phasing. (It phases in or out before you untap during each of your untap steps. While it's phased out, it's treated as though it doesn't exist.)\nAt the beginning of your end step, flip a coin. If you win the flip, take an extra turn after this one.",
  life_modifier: "-3",
  hand_modifier: "-1",
  colors: [],
  color_identity: [],
  keywords: [],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "not_legal",
    gladiator: "not_legal",
    pioneer: "not_legal",
    explorer: "not_legal",
    modern: "not_legal",
    legacy: "not_legal",
    pauper: "not_legal",
    vintage: "not_legal",
    penny: "not_legal",
    commander: "not_legal",
    oathbreaker: "not_legal",
    brawl: "not_legal",
    historicbrawl: "not_legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "not_legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["mtgo"],
  reserved: false,
  foil: true,
  nonfoil: true,
  finishes: ["nonfoil", "foil"],
  oversized: false,
  promo: false,
  reprint: false,
  variation: false,
  set_id: "f8778e61-ae6b-43ee-a611-f042439fa737",
  set: "pmoa",
  set_name: "Magic Online Avatars",
  set_type: "vanguard",
  set_uri: "https://api.scryfall.com/sets/f8778e61-ae6b-43ee-a611-f042439fa737",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Apmoa&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/pmoa?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/3b81d1a1-487d-40b7-88f5-691d2a01dad5/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Adf33f381-ff74-4ef2-8396-443019590006&unique=prints",
  collector_number: "53",
  digital: true,
  rarity: "rare",
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "UDON",
  artist_ids: ["1aa5b0cc-259b-40f0-b236-6866876b917a"],
  illustration_id: "ca12d67d-86fc-4023-990b-a73e18ceb210",
  border_color: "black",
  frame: "2015",
  full_art: false,
  textless: false,
  booster: false,
  story_spotlight: false,
  prices: {
    usd: null,
    usd_foil: null,
    usd_etched: null,
    eur: null,
    eur_foil: null,
    tix: "2.35",
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=182275",
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Frenetic+Efreet+Avatar&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Frenetic+Efreet+Avatar&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Frenetic+Efreet+Avatar",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/search/magic/product?productLineName=magic&q=Frenetic+Efreet+Avatar&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall&view=grid",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Frenetic+Efreet+Avatar&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards/38?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
