import { ScryfallCard } from "../../../Card";

const Snapdax: ScryfallCard.Mutate = {
  object: "card",
  id: "51fdeeb7-9868-4fc2-9c53-806244cd5488",
  oracle_id: "b2b78623-5a10-4ef7-b983-3d82478269c3",
  multiverse_ids: [479729],
  mtgo_id: 80427,
  arena_id: 71276,
  tcgplayer_id: 212023,
  cardmarket_id: 451113,
  name: "Snapdax, Apex of the Hunt",
  lang: "en",
  released_at: "2020-04-24",
  uri: "https://api.scryfall.com/cards/51fdeeb7-9868-4fc2-9c53-806244cd5488",
  scryfall_uri: "https://scryfall.com/card/iko/209/snapdax-apex-of-the-hunt?utm_source=api",
  layout: "mutate",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/5/1/51fdeeb7-9868-4fc2-9c53-806244cd5488.jpg?1591228256",
    normal: "https://cards.scryfall.io/normal/front/5/1/51fdeeb7-9868-4fc2-9c53-806244cd5488.jpg?1591228256",
    large: "https://cards.scryfall.io/large/front/5/1/51fdeeb7-9868-4fc2-9c53-806244cd5488.jpg?1591228256",
    png: "https://cards.scryfall.io/png/front/5/1/51fdeeb7-9868-4fc2-9c53-806244cd5488.png?1591228256",
    art_crop: "https://cards.scryfall.io/art_crop/front/5/1/51fdeeb7-9868-4fc2-9c53-806244cd5488.jpg?1591228256",
    border_crop: "https://cards.scryfall.io/border_crop/front/5/1/51fdeeb7-9868-4fc2-9c53-806244cd5488.jpg?1591228256",
  },
  mana_cost: "{1}{R}{W}{B}",
  cmc: 4.0,
  type_line: "Legendary Creature — Dinosaur Cat Nightmare",
  oracle_text:
    "Mutate {2}{B/R}{W}{W} (If you cast this spell for its mutate cost, put it over or under target non-Human creature you own. They mutate into the creature on top plus all abilities from under it.)\nDouble strike\nWhenever this creature mutates, it deals 4 damage to target creature or planeswalker an opponent controls and you gain 4 life.",
  power: "3",
  toughness: "5",
  colors: ["B", "R", "W"],
  color_identity: ["B", "R", "W"],
  keywords: ["Mutate", "Double strike"],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "legal",
    gladiator: "legal",
    pioneer: "legal",
    explorer: "legal",
    modern: "legal",
    legacy: "legal",
    pauper: "not_legal",
    vintage: "legal",
    penny: "legal",
    commander: "legal",
    oathbreaker: "legal",
    brawl: "not_legal",
    historicbrawl: "legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "not_legal",
  },
  games: ["arena", "paper", "mtgo"],
  reserved: false,
  foil: true,
  nonfoil: true,
  finishes: ["nonfoil", "foil"],
  oversized: false,
  promo: false,
  reprint: false,
  variation: false,
  set_id: "19feda43-15ab-427e-a0e4-148a4bf2b03a",
  set: "iko",
  set_name: "Ikoria: Lair of Behemoths",
  set_type: "expansion",
  set_uri: "https://api.scryfall.com/sets/19feda43-15ab-427e-a0e4-148a4bf2b03a",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Aiko&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/iko?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/51fdeeb7-9868-4fc2-9c53-806244cd5488/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Ab2b78623-5a10-4ef7-b983-3d82478269c3&unique=prints",
  collector_number: "209",
  digital: false,
  rarity: "mythic",
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "Viktor Titov",
  artist_ids: ["2270c0b0-afb4-42b0-bcb6-25fe4ad6eef2"],
  illustration_id: "ed31dd64-fc66-47dd-9d7c-edd2b4599b0f",
  border_color: "black",
  frame: "2015",
  frame_effects: ["legendary"],
  security_stamp: "oval",
  full_art: false,
  textless: false,
  booster: true,
  story_spotlight: false,
  edhrec_rank: 8354,
  penny_rank: 10015,
  preview: {
    source: "GameSpot",
    source_uri: "https://www.gamespot.com/articles/magic-the-gathering-check-out-new-ikoria-lair-of-b/1100-6475447/",
    previewed_at: "2020-04-02",
  },
  prices: {
    usd: "0.40",
    usd_foil: "0.56",
    usd_etched: null,
    eur: "0.87",
    eur_foil: "1.49",
    tix: "0.02",
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=479729",
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Snapdax%2C+Apex+of+the+Hunt&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Snapdax%2C+Apex+of+the+Hunt&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Snapdax%2C+Apex+of+the+Hunt",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/product/212023?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Snapdax%2C+Apex+of+the+Hunt&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards/80427?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
