import { ScryfallCard } from "../../../../Card";

// Urborg
const Urborg: ScryfallCard.Normal = {
  object: "card",
  id: "9e1a9e38-6ffc-490f-b0be-23ba4e8204c6",
  oracle_id: "db6174d7-211d-4817-b8e4-8384594c83f9",
  multiverse_ids: [509652],
  mtgo_id: 86949,
  tcgplayer_id: 234275,
  cardmarket_id: 548301,
  name: "Urborg, Tomb of Yawgmoth",
  lang: "en",
  released_at: "2021-03-19",
  uri: "https://api.scryfall.com/cards/9e1a9e38-6ffc-490f-b0be-23ba4e8204c6",
  scryfall_uri: "https://scryfall.com/card/tsr/287/urborg-tomb-of-yawgmoth?utm_source=api",
  layout: "normal",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/front/9/e/9e1a9e38-6ffc-490f-b0be-23ba4e8204c6.jpg?1619399578",
    normal: "https://cards.scryfall.io/normal/front/9/e/9e1a9e38-6ffc-490f-b0be-23ba4e8204c6.jpg?1619399578",
    large: "https://cards.scryfall.io/large/front/9/e/9e1a9e38-6ffc-490f-b0be-23ba4e8204c6.jpg?1619399578",
    png: "https://cards.scryfall.io/png/front/9/e/9e1a9e38-6ffc-490f-b0be-23ba4e8204c6.png?1619399578",
    art_crop: "https://cards.scryfall.io/art_crop/front/9/e/9e1a9e38-6ffc-490f-b0be-23ba4e8204c6.jpg?1619399578",
    border_crop: "https://cards.scryfall.io/border_crop/front/9/e/9e1a9e38-6ffc-490f-b0be-23ba4e8204c6.jpg?1619399578",
  },
  mana_cost: "",
  cmc: 0.0,
  type_line: "Legendary Land",
  oracle_text: "Each land is a Swamp in addition to its other land types.",
  colors: [],
  color_identity: [],
  keywords: [],
  produced_mana: ["B"],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "not_legal",
    gladiator: "not_legal",
    pioneer: "legal",
    explorer: "not_legal",
    modern: "legal",
    legacy: "legal",
    pauper: "not_legal",
    vintage: "legal",
    penny: "not_legal",
    commander: "legal",
    oathbreaker: "legal",
    brawl: "not_legal",
    historicbrawl: "not_legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "legal",
    oldschool: "not_legal",
    premodern: "not_legal",
    predh: "legal",
  },
  games: ["paper", "mtgo"],
  reserved: false,
  foil: true,
  nonfoil: true,
  finishes: ["nonfoil", "foil"],
  oversized: false,
  promo: false,
  reprint: true,
  variation: false,
  set_id: "11e90d1b-0502-43e6-b056-e24836523c13",
  set: "tsr",
  set_name: "Time Spiral Remastered",
  set_type: "masters",
  set_uri: "https://api.scryfall.com/sets/11e90d1b-0502-43e6-b056-e24836523c13",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Atsr&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/tsr?utm_source=api",
  rulings_uri: "https://api.scryfall.com/cards/9e1a9e38-6ffc-490f-b0be-23ba4e8204c6/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Adb6174d7-211d-4817-b8e4-8384594c83f9&unique=prints",
  collector_number: "287",
  digital: false,
  rarity: "rare",
  flavor_text:
    '"Yawgmoth\'s corpse is a wound in the universe. His foul blood seeps out, infecting the land with his final curse."\n—Lord Windgrace',
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "John Avon",
  artist_ids: ["798f3932-30e0-4420-aa3f-db4d613f89ca"],
  illustration_id: "28d2ea86-5021-4f36-a5ec-028dae5bc71d",
  border_color: "black",
  frame: "2015",
  frame_effects: ["legendary"],
  security_stamp: "oval",
  full_art: false,
  textless: false,
  booster: true,
  story_spotlight: false,
  edhrec_rank: 56,
  preview: {
    source: "Commander Rules Committee",
    source_uri: "https://mtgcommander.net/index.php/2021/03/04/time-spiral-remastered-previews/",
    previewed_at: "2021-03-04",
  },
  prices: {
    usd: "31.03",
    usd_foil: "44.00",
    usd_etched: null,
    eur: "26.56",
    eur_foil: "32.97",
    tix: "1.57",
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=509652",
    tcgplayer_infinite_articles:
      "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Urborg%2C+Tomb+of+Yawgmoth&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks:
      "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Urborg%2C+Tomb+of+Yawgmoth&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Urborg%2C+Tomb+of+Yawgmoth",
  },
  purchase_uris: {
    tcgplayer:
      "https://www.tcgplayer.com/product/234275?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket:
      "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Urborg%2C+Tomb+of+Yawgmoth&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder:
      "https://www.cardhoarder.com/cards/86949?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall",
  },
};
